- pqarrow/arrow.go
- pqarrow/arrow_test.go
- query/engine.go
- query/logicalplan/logicalplan.go
- query/logicalplan/optimize.go
- query/logicalplan/optimize_test.go
- query/physicalplan/physicalplan.go
- table.go
- table_test.go
> Add distinct push down query optimization

- dynparquet/dynamiccolumns.go
- dynparquet/dynamiccolumns_test.go
- table.go
This took much longer to find than I'd like to admit.
> Fix parsing of dynamic column strings with empty dynamic columns

- db.go
- table_test.go
> Move DB struct to go.uber.org/atomic

- aggregate_test.go
- db.go
- granule.go
- table.go
- table_test.go
- tx_list.go
Addresses issue #6 
Replaces the active list with a high watermark.
> 6 high water mark

- table_test.go
This is a follow-up from the previous PRs of introducing the atomic package.
> Use table.active.Index() in table_test

- aggregate_test.go
- db.go
- distinct_test.go
- filter_test.go
- granule.go
- table.go
- table_test.go
> remove panics from storage

- table.go
> pass logger along in new blocks

- aggregate_test.go
- binaryscalarexpr.go
- db.go
- distinct_test.go
- dynparquet/concat.go
- dynparquet/nil_chunk.go
- dynparquet/reader.go
- dynparquet/row.go
- dynparquet/schema.go
- filter_test.go
- go.mod
- go.sum
- pqarrow/arrow.go
- table.go
- table_test.go
> Make inserts accept serialized parquet buffers

- dynparquet/schema.go
This appears to be a bug in parquet-go that I haven't been able to track
down yet, but for some reason copying appears to be faulty in certain
situations when copying an in-memory buffer to a persistent buffer.
However, when writing row by row, it works. I could see this being a
bug in the optimization paths CopyRows attempts to take copying 
multiple rows at once or even entire pages.
> dynparquet: Fix buffer serialization

- distinct_test.go
- query/engine.go
- query/logicalplan/builder.go
- query/logicalplan/builder_test.go
- query/logicalplan/expr.go
- query/logicalplan/logicalplan.go
- query/logicalplan/optimize.go
- query/logicalplan/optimize_test.go
- query/physicalplan/aggregate.go
- query/physicalplan/binaryscalarexpr.go
- query/physicalplan/filter.go
- query/physicalplan/physicalplan.go
- query/physicalplan/physicalplan_test.go
- query/physicalplan/project.go
- query/physicalplan/regexpfilter.go
Binary projections allow synthesizing columns in a result such as `duration > 0` projecting a boolean column.
> *: Add binary projections

- table.go
Signed-off-by: Ben Ye <ben.ye@bytedance.com>
> check left expr result when filtering granule with binary and op

- examples/simple.go
added an example to insert data and retrieve it
> create simple example

- query/physicalplan/filter.go
Reference: 
https://github.com/polarsignals/arcticdb/blob/25ef30a7de155b842e40b5f0260cc1ea1b6bbbc3/query/physicalplan/filter_test.go#L38-L41
> Fix the comment of buildIndexRanges

- table.go
Should fix the problem detailed in #81
> Fix problem with concurrent index Delete()

- table.go
Adds a metrics to track number of block rotations.
> add metric for block rotations

- filter_test.go
- query/physicalplan/project.go
- table_test.go
Adds dynamic projections allowing us to perform queries for all dynamic columns
> Dynamic projections

- distinct_test.go
- pqarrow/arrow.go
Adds support for dynamic distinct expressions
> Support dynamic distinct

- distinct_test.go
- pqarrow/arrow.go
Fixes https://github.com/parca-dev/parca/issues/1417
> Fix panic in distinct queries where all values are null

- db_test.go
- store.go
- table.go
- table_test.go
Uses GetRange to create an `io.ReaderAt` to not have to read the full file into memory to process it.
> ReadAt storage

- dynparquet/schema.go
Realized the function I had written already existed
> remove code that was redundant

- db.go
Fixes: #133
Signed-off-by: heylongdacoder <heylongdacoder@gmail.com>
> Wrap database logger with database name

- wal/wal.go
- wal/wal_test.go
Signed-off-by: Arunprasad Rajkumar <ar.arunprasad@gmail.com>
> WAL replay fails when WAL dir is empty

- db.go
- db_test.go
For a given DB and Table, a read only Table will be created on DB initialisation. During WAL replay for NewTableBlock entry, another Table instance is being created with the same name which causes panic while registering table metrics. This commit fixes the problem by converting existing read only table into normal table.
Signed-off-by: Arunprasad Rajkumar <ar.arunprasad@gmail.com>
> WAL replay with bucket storage causes panic while registering table metrics

- pqarrow/arrow.go
This commit uses a column chunk's column index to optimize distinct queries
where there is a single value in the chunk (across all pages) of a
dictionary-encoded column. In this case, a dictionary can be constructed with
the value stored in the index, avoiding an expensive page decompression step.
```
QueryTypes-8     169ms ±11%     133ms ±18%  -21.14%  (p=0.049 n=10+3)
name          old alloc/op   new alloc/op   delta
QueryTypes-8     443MB ± 0%     436MB ± 0%   -1.54%  (p=0.007 n=10+3)
name          old allocs/op  new allocs/op  delta
QueryTypes-8     1.13M ± 0%     1.05M ± 0%   -6.78%  (p=0.007 n=10+3)
```
Closes #158 
cc @metalmatze @thorfour
> pqarrow: use ColumnIndex to answer distinct queries at the scan level

- aggregate_test.go
- query/logicalplan/expr.go
- query/physicalplan/aggregate.go
Signed-off-by: Ben Ye <ben.ye@bytedance.com>
> Support count aggregate function

- aggregate_test.go
- bench_test.go
- db.go
- db_test.go
- distinct_test.go
- examples/simple.go
- filter_test.go
- query/engine.go
- table_test.go
Makes logging, tracing, and metrics options instead of required params.
> Obsv as options

- pqarrow/arrow.go
- pqarrow/writer/writer.go
The first two commits are #195. The other commits have been split out into this PR to make reviewing that easier, so if you haven't already, please review #195. The additional performance benefits this PR offers us are:
```
QueryTypes-8    5.31ms ± 1%    4.87ms ± 1%  -8.26%  (p=0.008 n=5+5)
QueryMerge-8    18.7ms ± 0%    18.5ms ± 3%     ~     (p=0.151 n=5+5)
QueryRange-8    11.3ms ± 2%    10.6ms ± 3%   -6.02%  (p=0.016 n=4+5)
name          old alloc/op   new alloc/op   delta
QueryTypes-8    5.62MB ± 0%    5.61MB ± 0%   -0.17%  (p=0.008 n=5+5)
QueryMerge-8    49.7MB ± 0%    43.0MB ± 0%  -13.51%  (p=0.008 n=5+5)
QueryRange-8    22.6MB ± 0%    15.9MB ± 0%  -29.65%  (p=0.008 n=5+5)
name          old allocs/op  new allocs/op  delta
QueryTypes-8 …
```
> pqarrow: more optimizations on top of ParquetConverter

- distinct_test.go
- pqarrow/arrow.go
- query/physicalplan/project.go
Previously, the scan layer would pre-compute binary distinct expressions at a row group granularity. Downstream projections would only evaluate the expression if all results were null (i.e. no optimization was able to be made).
This logic broke down when we started accumulating row group conversion results since binary expression evaluations could be partially optimized (i.e. we could fail to optimize some row groups in a record), therefore rows belonging to a row group where the expression was not pre-evaluated would result in the result for that row automatically evaluating to NULL.
This commit changes the logic to only skip evaluation when the expression result has been fully computed by the scan layer. In case of partial scan layer results, those are merged into the projection …
> physicalplan/pqarrow: handle partially pre-computed results in Project

- .github/workflows/go.yml
- .github/workflows/golangci-lint.yml
- .golangci.yml
- go.mod
- granule.go
- part_list.go
- table.go
- tx_list.go
This is all @Mihai22125 work from https://github.com/polarsignals/frostdb/pull/160
Just updated the ci files to use 1.19, and rebased on top of main.
> Atomic fixes

- table.go
Addressing comment from https://github.com/polarsignals/frostdb/pull/214
> buffer the number of rows for a row group if given

- dynparquet/schema.go
This is a useful util. Exposing the pkg API
> expose merge dynamic row groups

- query/physicalplan/aggregate.go
Since maps return a random ordering, this screws up the record schema ordering, which results in bad aggregations
> Range over a list instead of map

- table.go
This was preventing compactions from starting
> don't perform CAS on pruned, since compactor already checks

- bench_test.go
This commit moves BenchmarkQuery{Types,Merge,Range} into a single top-level BenchmarkQuery that then runs each scenario in a sub-benchmark. This allows setting up the db only once and then sharing it across benchmarks. Doing this seems to also reduce the number of times the setup code is run to one time. Previously, it seems like golang's benchmark runtime would run setup multiple times.
```
name           time/op
Query/Types-8  3.77ms ± 1%
Query/Merge-8  12.4ms ± 1%
Query/Range-8  4.04ms ± 0%
name           alloc/op
Query/Types-8  5.69MB ± 0%
Query/Merge-8  74.9MB ± 0%
Query/Range-8  16.3MB ± 0%
name           allocs/op
Query/Types-8   93.4k ± 0%
Query/Merge-8    301k ± 0%
Query/Range-8   57.7k ± 0%
```
> frostdb: move all BenchmarkQuery* benchmarks into one benchmark

- logictest/logic_test.go
- logictest/runner.go
This allows a user to write an implementation of a database and test it against logictest files.
> logictest: add LogictestDB interface to abstract operations

- README.md
Signed-off-by: Palash Nigam <npalash25@gmail.com>
> README: fix typo and example code snippet

- db.go
- db_test.go
- query/logicalplan/logicalplan.go
- query/logicalplan/logicalplan_test.go
- query/physicalplan/physicalplan.go
- query/physicalplan/physicalplan_test.go
Prevent queries from causing a panic on a table that doesn't exist
> Fix table reader panics

- table.go
Especially then row group event may be useful here.
> Add tracing to TableBlock/RowGroupIterator

- dynparquet/row.go
- dynparquet/row_test.go
- dynparquet/schema.go
This was caused by using the general parquet schema of all columns and calling its comparison function with rows of just the sorting columns, causing an index OOB panic in some cases. This commit creates a parquet schema of just the sorting columns for the comparison.
> dynparquet: fix out of bounds comparison panic

- db.go
- dynparquet/schema.go
> parse schema proto: refactor into helper func; handle default case

- query/physicalplan/ordered_aggregate_test.go
> physicalplan: skip TestOrderedAggregate due to flake

- query/physicalplan/physicalplan.go
This is easier to reason about since by using a post visit strategy the plan is built from the scan layer up, rather than the result layer down as was previously done. This also follows our data flow in the execution engine.
> physicalplan: change from a pre to a post visit plan building strategy

- pqarrow/arrowutils/groupranges.go
- pqarrow/arrowutils/nullarray.go
- query/physicalplan/ordered_aggregate.go
- query/physicalplan/ordered_aggregate_test.go
This required adding some more fields to the OrderedAggregate to keep track of which columns we have/have not seen.
> physicalplan: make OrderedAggregate work in the presence of dynamic columns

- wal/wal.go
- wal/wal_test.go
These errors can be encountered due to torn writes not fully writing tailing WAL entries. The approach this commit takes is to delete the last file in the directory, which should be where the corruption is, before reattempting an Open.
cc @brancz 
Addresses #311
> wal: try repair the wal when encountering log corrupt error

- query/physicalplan/physicalplan.go
This allows Build to work on arbitrary input plans.
> physicalplan: allow specifying input to Build

- bench_test.go
BenchmarkQuery was previously hardcoded to work only with WALs generated by parca. This commit allows us to use WALs generated by e.g. prod storage.
Additionally, this commit adds the Labels and Values queries to the benchmark so that we can start tracking them.
> frostdb: make BenchmarkQuery more robust

- compaction.go
This step was elided by mistake.
> frostdb: apply compaction options

- dynparquet/reader.go
Address #331. The result looks something like:
```
row groups: 1  total rows: 9
---
[name]           [sample_type]  [sample_unit]  [period_type]  [period_unit]  [labels.agen...  [labels.app_...  [labels.app_...  [labels.app_...  [labels.app_...  [labels.app_...  [labels.app_...  [labels.cgro...  [labels.comm]    [labels.cont...  [labels.cont...  [labels.cont...  [labels.exec...  [labels.k8s_...  [labels.kern...  [labels.name...  [labels.node]    [labels.oper...  [labels.oper...  [labels.pid]   [labels.pod]     [labels.pod_...  [labels.ppid]  [labels.prom...  [labels.stat...  [labels.syst...  [timestamp]
parca_agent_cpu  samples        count          cpu            nanoseconds    0b3a3e99501c...  prometheus       k8s              prometheus-o...  prometheus       kube-prometheus  2.39.1 …
```
> dynparquet: add String method to SerializedBuffer

- wal/wal.go
- wal/wal_test.go
This PR proposes a couple of changes to the WAL to protect from getting into unwanted state.
> wal: miscellaneous fixes

- db.go
When replaying writes, we would only check if the table did not exist to skip replaying a write, implying that the new table block entry had been truncated and therefore persisted. However, sometimes the database can only truncate entries if ALL tables have been persisted and only then up to the minimum transaction persisted across all tables. This means that even if a block belonging to a larger table is persisted, writes belonging to this block might not be truncated from the WAL yet. This commit skips these writes if it sees that the block the writes belong to were already persisted, reducing unnecessary memory pressure on the databse.
> frostdb: skip replaying WAL writes for tables that have already been persisted

- dynparquet/concat.go
- dynparquet/reader.go
- dynparquet/schema.go
> dynparquet: add fmt.Stringer interface to DynamicRowGroup

- dynparquet/row.go
- granule.go
- logictest/testdata/exec/aggregate/aggregate_nulls
- table.go
This commit checks that an invariant we expect, that rows are sorted on insert, is upheld. If not, this commit increments a metric and sorts the rows.
> *: check rows are sorted on insert

- binaryscalarexpr.go
- logictest/testdata/exec/filter/filter
- pqarrow/parquet.go
- query/physicalplan/binaryscalarexpr.go
> Add support for filtering for IS NULL or IS NOT NULL

- table.go
Effectively a non-recording table like Postgres
> Add table option to disable WAL for the given table

- .github/workflows/golangci-lint.yml
- binaryscalarexpr_test.go
This commit also bumps the golangci-lint version to fix CI issues.
> frostdb: fix binaryscalarexpr_test.go lint error

- table.go
Using the context used for the write causes snapshots to be cancelled in cases where the caller cancels the context after the write is complete. To avoid this, this commit uses context.Background. A future patch will introduce graceful interruptions of snapshots.
> frostdb: use context.Background for snapshot goroutines

- db.go
I believe this is what's causing the following panic in production:
```
2023-03-13 09:43:07    panic: programming error; unable to find granule for part
2023-03-13 09:43:07    
2023-03-13 09:43:07    goroutine 783 [running]:
2023-03-13 09:43:07    github.com/polarsignals/frostdb.addPartToGranule({0xc016774870, 0x1, 0x2?}, 0x2?)
2023-03-13 09:43:07        github.com/polarsignals/frostdb@v0.0.0-20230313133957-5ca7a202540c/table.go:1407 +0x128
2023-03-13 09:43:07    github.com/polarsignals/frostdb.(*TableBlock).compactGranule(0xc001080d00, 0xc02a5edf40, 0xc0000be4b0)
2023-03-13 09:43:07        github.com/polarsignals/frostdb@v0.0.0-20230313133957-5ca7a202540c/compaction.go:440 +0x68e
2023-03-13 09:43:07    github.com/polarsignals/frostdb.(*TableBlock).compact.func1({0x3276d00?, …
```
> db: fixes to recover

- binaryscalarexpr.go
- binaryscalarexpr_test.go
This commit fixes equality operations against ColumnChunks. The operation would previously return that a value in the column chunk might return true when in fact the column chunk could be discarded.
This greatly increases performance because we avoid decompressing unnecessary row groups:
```
name            old time/op    new time/op    delta
Query/Merge-8     61.0ms ± 2%    44.9ms ± 3%  -26.42%  (p=0.000 n=10+10)
Query/Range-8     57.9ms ± 1%    30.4ms ± 2%  -47.60%  (p=0.000 n=10+10)
name            old alloc/op   new alloc/op   delta
Query/Merge-8     1.06GB ± 0%    0.80GB ± 0%  -23.88%  (p=0.000 n=10+10)
Query/Range-8      190MB ± 0%      95MB ± 0%  -49.94%  (p=0.000 n=10+8)
name            old allocs/op  new allocs/op  delta
Query/Merge-8       917k ± 0%      445k ± 0%  -51.47% …
```
> frostdb: fix BinaryScalarOperation equality operations

- table.go
Closes #405 
Previously we were splitting every inserted record into N parts where N was the number of rows in the record.
Now we'll insert contiguous rows together in the same part if they belong to the same granule.
> rewrite record insert to insert larger slices

- pqarrow/parquet.go
From the comment here: https://github.com/polarsignals/frostdb/pull/415
> fix null append for dynamic columns

- compaction.go
- query/physicalplan/aggregate.go
This addresses the arrow panics reported in #425 
It has compaction obtain a write block which causes the block rotation to wait for a compaction to finish. This will prevent the serialize command from accessing arrow records that have been released by compaction.
It also addresses a unit test failure reported in #419 
Fixes the array overflow mismatch by correctly rolling back the initially created aggregation, whereas before it was leaving that extra aggregation even though it had to create a new set.
> Fix 425 arrow panic

- db.go
I sometimes see that the wal directory has not been cleaned up. I think the logging added by this PR is beneficial without being verbose.
> db: add logging on Close to get more visibility on graceful shutdown

- wal/wal.go
- wal/wal_test.go
Previously, we would synchronously truncate even though we asynchronously wrote
to the WAL. This caused truncations to fail with high likelihood given that the
transaction to truncate at was likely not yet logged.
Closes #431
> wal: perform truncation in run

- wal/wal.go
- wal/wal_test.go
A previous commit moved truncation to the run loop. However, the code would only perform a truncation if a new record with the truncate txn was popped off the heap. There could be cases where the record to truncate at has already been written to the WAL, which is handled by this commit.
> wal: fix race on truncation

- pqarrow/arrow.go
- pqarrow/arrow_test.go
- pqarrow/arrowutils/nullarray.go
- pqarrow/builder/listbuilder.go
- pqarrow/builder/optbuilders_test.go
- pqarrow/builder/recordbuilder.go
- pqarrow/builder/utils.go
- pqarrow/convert/convert.go
- pqarrow/convert/convert_test.go
- query/physicalplan/aggregate.go
- query/physicalplan/distinct.go
- query/physicalplan/ordered_aggregate.go
This reverts commit 58a5eb8be8aab1fbe6b2e37166fa934ddbba2f2b.
> Revert "fix nullable list support (#438)"

- snapshot.go
This prevents races with compaction/persistence.
Closes #425
> *: obtain ActiveWriteBlock in snapshots

- table_test.go
Test fails if `650268f` is reverted
```
thor@thors-MacBook-Pro frostdb % go test -v -run Compact_Repeated
=== RUN   Test_Compact_Repeated
sync.go:69: level=debug db=test msg="compaction complete" duration=6.848333ms l0Before="[sz=60 B,cnt=1]" l1Before="[sz=0 B,cnt=0]" l1After="[sz=1.9 KiB,cnt=3]" overlaps=0 splits=2
table_test.go:1717:
Error Trace:	/Users/thor/go/src/github.com/polarsignals/frostdb/table_test.go:1717
/Users/thor/go/src/github.com/polarsignals/frostdb/table.go:878
/Users/thor/go/pkg/mod/golang.org/x/sync@v0.1.0/errgroup/errgroup.go:75
/opt/homebrew/Cellar/go/1.20.4/libexec/src/runtime/asm_arm64.s:1172
Error:      	Should be true
Test:       	Test_Compact_Repeated
sync.go:69: level=info db=test msg="closing DB"
sync.go:69: level=info db=test msg="closed all tables"
--- …
```
> unit test: Ensure repeated columns are compacted correctly

- query/physicalplan/aggregate.go
Attributes:
- num rows
- finalstage
> Added some tracing attributes to the Finish step of the hash agggregate

- query/physicalplan/aggregate.go
Previously we were appending all the list values and then hashing them. This becomes extremely inefficient when using really large lists. Instead we just hash the list values directly.
Below is a benchmark for a normal aggregate query against 12h of real profiling data.
```bash
name              old time/op    new time/op    delta
_PreAggregate-10     6.56s ± 2%     4.81s ± 3%  -26.76%  (p=0.000 n=10+10)
name              old alloc/op   new alloc/op   delta
_PreAggregate-10    33.1GB ± 0%    14.6GB ± 0%  -55.94%  (p=0.000 n=8+10)
name              old allocs/op  new allocs/op  delta
_PreAggregate-10      174M ± 0%      162M ± 0%   -6.99%  (p=0.000 n=10+9)
```
> aggregate: directly hash the list values

- go.mod
- go.sum
- pqarrow/arrow_test.go
Brings in https://github.com/segmentio/parquet-go/pull/508
> bump parquet-go

- query/memory.go
This reverts commit e554838a99595b73d848197f8a558454ac5c1d65.
> Revert "memory allocator: handle accounting for shrink (#467)"

- db.go
When opening a database with an on-disk WAL, the first instantiation is a side-effect of an internal `DB` call in order to recover from wal/snapshots. It doesn't make sense to pass user options through this frostdb.New call since the user needs to specify per-db options.
Instead, this commit applies options to a db even if the db already exists, which handles cases where an internal db creation had no options, but the first user-triggered DB call does.
> db: apply options when re-opening database

- wal/wal.go
- wal/wal_test.go
> wal: time out Close 

- db.go
useful for resetting a database if something becomes corrupt
> remove storage from a database

- aggregate_test.go
- query/logicalplan/validate.go
- query/physicalplan/aggregate.go
Adds support for performing aggregations on dynamic columns.
> Aggregation dyn cols

- db.go
- pqarrow/parquet.go
- query/physicalplan/binaryscalarexpr.go
This PR adds a method to iterate over all tables and adds support for greater than expressions on uint64 arrays.
> *: misc additions

- binaryscalarexpr.go
- binaryscalarexpr_test.go
Previously, nulls were only handled for the logicalplan.OpEq operator. There were cases where the presence of nulls in the application of other operators (e.g. logicalplan.OpGt) would lead to an unsupported value panic in the comparison function. Indeed, null comparisons are undefined according to SQL semantics so the safest bet right now is to simple have null values pass the check and delegate the filtering to the execution engine.
There is probably some optimizations we can do here once we define the semantics we want, but this commit opts for safety first as a first step.
Closes https://github.com/polarsignals/polarsignals/issues/2508
> *: handle column chunks with contained nulls in BinaryScalarOperation

- db.go
We would previously recover DBs in parallel, however, because the ColumnStore mutex was held during this replay, WAL replays would actually happen serially.
> *: release store mutex when replaying WAL

- bench_test.go
- snapshot.go
Previously, we were reading rows one by one from parts and writing them to disk on snapshot. However, we already have a serialized version of the parquet bytes by accessing the parquet file. This commit uses io.Copy to copy those bytes directly to disk. This commit halves snapshot time.
```
$ benchstat benchmain benchcopy
goos: darwin
goarch: arm64
│  benchmain  │             benchcopy             │
│   sec/op    │   sec/op    vs base               │
Snapshot-12   36.59 ± 19%   18.91 ± 2%  -48.31% (p=0.002 n=6)
```
> snapshot: use io.Copy instead of copying parts row by row

- query/physicalplan/aggregate.go
Previously an error would leave those arrays stranded
> fix leak: defer release group by array

- db.go
Previously, we were using only on thread to read WAL entries and write to the frostdb instance. Writing is a very expensive part of replaying data, so this commit changes to spawn a limited pool of goroutines to perform the writes.
Additionally, this commit waits to start the compactor pool until after the replay has finished. This reduces compaction memory usage and avoids writes competing with compaction.
```
goos: darwin
goarch: arm64
│ benchmain  │    benchconclimitdefercompact     │
│   sec/op   │   sec/op    vs base               │
Replay-12   66.41 ± 2%   20.29 ± 4%  -69.45% (p=0.002 n=6)
│   benchmain   │     benchconclimitdefercompact      │
│     B/op      │     B/op      vs base               │
Replay-12   239.28Gi ± 1%   48.35Gi ± 0% …
```
> db: write WAL writes in parallel and don't start compaction until after replay

- db.go
Otherwise these compactions race, and db setup might not wait until the table is actually compacted.
> db: start compactor pool after potential user-specified compaction

- aggregate_test.go
- bench_test.go
- compaction_test.go
- db.go
- db_test.go
- logictest/logic_test.go
- logictest/runner.go
- snapshot_test.go
- table.go
- table_test.go
Insertion via Parquet files is now officially unsupported
> remove InsertBuffer

- wal/wal.go
Previously, if we found a txn below the nextTx, we would pop it but continue waiting for the timer to fire again before popping the next one. This is not necessary and can lead to high memory usage.
This commit also avoids pushing these requests to the queue in the first place.
> wal: don't wait for ticker to fire to clear pending txns

- wal/wal.go
Previously, when performing a truncation at a given transaction n, there could be buffered entries with txns < n that had not yet been written to the WAL, resulting in log spam of the form "WAL cannot log a txn ID that has already been seen". This commit removes these buffered entries after truncation.
Closes https://github.com/polarsignals/polarsignals/issues/2835
> wal: drop buffered entries after truncation

- db.go
> Reduces the API contract of the DataSink interface to be only what we

- db.go
- db_test.go
This could previously cause panics of the type "duplicate metrics registration attempted".
Addresses https://github.com/polarsignals/polarsignals/issues/2917
> db: protect against concurrent database creations

- db.go
- Adds a method that returns all columnstore database names
- Adds an option to limit recovery concurrency
> *: misc additions to frostdb

- parts/part.go
- parts/part_test.go
> fix missing compaction parts

- db.go
> db: don't snapshot on close if the db will clear storage

- snapshot.go
This is good practice, and we're possibly retaining unnecessary memory here.
> snapshot: release arrow readers after use

- aggregate_test.go
Adds a test for duration aggregation
> add test for duration aggregation

- query/logicalplan/builder.go
- query/logicalplan/expr.go
- query/logicalplan/validate.go
> Make  Expr implement  fmt.Stringer interface

- dynparquet/schema.go
- table_test.go
I faced a challenge while writing a struct pointer to the table. I ended up building arrow record by hand and use `(*Table)InsertRecord`.
There is no technical reason why we can't support pointers to struct. We already use `reflect` to process the values.
This commit dereferences pointer values before processing them. Basically passing `Sample` or `(*Sample)` to `(*Table).Write` should behave the same.
> Support struct pointers on (*Table).Write

- aggregate_test.go
- db_test.go
- dynparquet/record_builder.go
- examples/aggregations/aggregations.go
- examples/simple/simple.go
- snapshot_test.go
- table.go
- table_test.go
This commit removes `(*Table).Write` in favor of `(*GenericTable[T]).Write`
`GenericTable` offers a lot of improvements from the previous API. One of the biggest advantage is there is no longer need to define schema before hand instead the schema is part of the struct that is written in the form of struct tags.
Example code has been refactored to use `map[string]T` for dynamic columns, however slice struct dynamic columns still works, this is intentional to avoid the PR from blowing out of proportion.
`GenericTable` embeds `Table` so from user perspective only few changes are needed to work with the new API.
Also 
Closes #623
> Remove (*Table)Write and introduce (*GenericTable[T]).Write

- README.md
The api has changed, this updates the README to point to new api.
> Update link to example on README

- logictest/logic_test.go
found this while lurking around.
> Remove unused function

- dynparquet/schema.go
- parts/arrow.go
- parts/part_test.go
- pqarrow/parquet.go
We have already removed `(*Table)Write`. There is no longer any use for this function.
> Remove dynparquet.ValuesToBuffer

- query/logicalplan/optimize.go
Comments should start with exported symbol name.
> Fix godoc comment on exported symbols

- query/logicalplan/optimize.go
Replace `golang.org/x/exp/slices` with standard library `slices` package
> Use slices package

- pqarrow/arrow.go
This commit adds `*array.String` handling inside `copyArrToBuilder` cases for both plain `*array.String` and dictionary of `*array.String` are handled.
Fixes #661
> fix handling of *array.String in ParquetConverter

- .github/workflows/buf.yml
- proto/frostdb/schema/v1alpha1/schema.proto
- proto/frostdb/schema/v1alpha2/schema.proto
- proto/frostdb/snapshot/v1alpha1/snapshot.proto
- proto/frostdb/table/v1alpha1/config.proto
I was working on protobuf files and noticed my vscode was formatting the files differently.
We already use buf for generating, it is reasonable to use buf for formatting as well. Strictly for consistency.
> buf format -w

- pqarrow/arrowutils/sort.go
This is my last pass before I move on to introduce the changes in `parca`
Benchmark result
```
goos: darwin
goarch: amd64
pkg: github.com/polarsignals/frostdb/pqarrow/arrowutils
│   old.txt    │           new.txt            │
│    sec/op    │   sec/op     vs base         │
SortRecord-8   7.492µ ± 10%   6.972µ ± 7%  ~ (p=0.093 n=6)
│  old.txt   │              new.txt              │
│    B/op    │    B/op     vs base               │
SortRecord-8   808.0 ± 0%   400.0 ± 0%  -50.50% (p=0.002 n=6)
│   old.txt   │              new.txt              │
│  allocs/op  │ allocs/op   vs base               │
SortRecord-8   15.000 ± 0%   8.000 ± 0%  -46.67% (p=0.002 n=6)
```
I really missed `errdefer` in `zig` manual release during `error` returns in …
> Reduce memory allocation in arrowutils.SortRecord

- db.go
- index/lsm_test.go
- table_test.go
We no longer manitain writes inside granules
> remove granule size setting

- query/logicalplan/validate.go
- table_test.go
> Support aggregating on a single dynamic column

- pqarrow/arrowutils/merge.go
I requested this change in code review , unfortunately the PR got merged while I was incapacitated.
The procedure went well, I'm supposed to rehab now, but I'm too bored to lay on bed all day. Will try to pick small tasks with less typing.
> fix MergeRecords comment

- table.go
> Pre hash columns before committing to wal

- pqarrow/arrowutils/sort.go
This is supplementary patch needed for #672. I am submitting it separately to simplify reviewing.
> Add Binary dictionary support for arrowutils.Take

- pqarrow/arrowutils/sort.go
This commit adds sorting `*array.Binary` and dictionary of `*array.Binary`. I wanted `GenericTable` to automatically sort records before write. This is the only blocker.
> Add support for sorting *array.Binary columns

- query/physicalplan/binaryscalarexpr.go
- query/physicalplan/binaryscalarexpr_test.go
> Fix arrayscalarcompute leak

- table.go
This allows the db to provide the semantics that if RotateBlock with skipPersist=true, that block won't be returned for reads once RotateBlock returns. Previously, RotateBlock would just add the block to pendingBlocks and delete it in a goroutine. Given no persistence happens, this was unnecessary.
> table: skip adding block to pending blocks if skipPersist=true

- store.go
Creating a span for each row group can create way too many spans.
> reduce the number of spans

- db_test.go
- query/logicalplan/logicalplan.go
- query/physicalplan/physicalplan.go
- table.go
This allows introducing different read modes such as ReadModeObjectStorage which reads only from object storage. WithInMemory is now WithReadMode(ReadModeInMemory).
> *: change WithInMemory physicalplan option to WithReadMode

- dynparquet/hashed.go
- query/logicalplan/validate.go
- query/physicalplan/project.go
We want to be able to project and aggregate (e.g. sum and count) with uint64 columns directly.
> Support uint64 projection and aggregation

- pqarrow/arrowutils/groupranges.go
- pqarrow/arrowutils/merge.go
- pqarrow/arrowutils/merge_test.go
- query/physicalplan/ordered_aggregate.go
- query/physicalplan/ordered_synchronizer.go
This allows to merge records in arbitrary orders and columns.
> pqarrow/arrowutils: Use SortingColumns in MergeRecords

- logictest/testdata/exec/aggregate/aggregate
- logictest/testdata/exec/filter/filter
- logictest/testdata/exec/limit/limit
- logictest/testdata/plan/aggregate/aggregate
- logictest/testdata/plan/filter/filter
- logictest/testdata/plan/limit/limit
- pqarrow/arrowutils/sort.go
- query/engine.go
- query/logicalplan/builder.go
- query/logicalplan/logicalplan.go
- query/logicalplan/validate.go
- query/physicalplan/limit.go
- query/physicalplan/physicalplan.go
- sqlparse/visitor.go
There's probably lots of opportunities to improve and push down limits with a query optimizer. 
We will follow up with PRs to improve this.
> Add LIMIT support to FrostDB queries

- .github/workflows/stale.yml
We shouldn't remove bugs just because we haven't gotten to them yet
> stalebot: Don't close old bugs

- gen/proto/go/frostdb/snapshot/v1alpha1/snapshot_vtproto.pb.go
I didn't see I updated this generated file.
This fixes it and commits what gets generated again.
> gen: Fix generated file

- tx_list_test.go
Just something I stumbled over.
> Use slices.IsSorted to compare slices

- renovate.json
Renovate doesn't respect the replace directive in go.mod Force it to
> renovate: respect not upgrading avro

- query/engine_test.go
- query/physicalplan/physicalplan.go
Reverts polarsignals/frostdb#861
> Revert "Fix query concurrency"

- pqarrow/arrowutils/sort.go
- pqarrow/arrowutils/sort_test.go
This commit adds both a TakeList function to reorder arrays of type List when sorting records, and improves TakeDict performance by inserting dict values directly and subsequently indices, to avoid materializing values. This especially speeds up cases where dictionaries have a low number of distinct values.
> arrowutils: add TakeList and improve TakeDict performance

- query/physicalplan/filter.go
Previously if array.Concatenate returned an error not all columns in the cols slice would be populated and would cause the deferred function to panic on Release.
This fixes that potential panic by appending to the cols array such that only the allocated columns are released.
> fix panic on Release

- db.go
When adding an index directory, we didn't account for it in DropDB, causing os.Remove to error with "directory is not empty". This commit simply iterates over all directory entries in the storage path and renames them, rather than only renaming a pre-specified subset. Additionally, Remove has been changed to RemoveAll in DropDB, which handles directories with elements still in them.
> *: future-proof DropDB

- pqarrow/arrow.go
- pqarrow/writer/writer.go
Currently, when converting a parquet page to an arrow record, all the writers would repeat the slow path of allocating a parquet.Values slice, read all values, and write them to their underlying builder. However, this code already existed one level above and is more efficient since it reuses a parquet.Values slice.
This commit removes the repetition from the writers and leaves only the concrete implementation of writing existing values to an arrow builder. Callers can also check if the ValueWriter implements the PageWriter interface, which can also offer a fast path for writing a parquet page directly.
The improvement is especially noticeable in Query/Values since the slow path would previously fall back to write all the page values, rather than just the dictionary values.
```
│ …
```
> pqarrow: centralize ReadValues when writing a page

- pqarrow/arrowutils/merge_test.go
- pqarrow/builder/utils.go
Contains #949 which should be merged first.
> pqarrow/arrowutils: Support merging nested lists and structs
