polarsignals/frostdb

dynparquet/schema.go

This is needed for the change to use the switch-case in https://github.com/parca-dev/parca/pull/835/

Add a Columns() to the schema

---

aggregate_test.go
query/physicalplan/aggregate.go

I believe this fixes the panic reported in https://github.com/polarsignals/arcticdb/issues/26

query/physicalplan: Fix aggregations of nil values

---

go.mod
go.sum

Now that https://github.com/apache/arrow/pull/12764 is merged, we can use the upstream again.

go.mod: Update apache/arrow to latest

---

filter.go

Signed-off-by: Ben Ye <ben.ye@bytedance.com>
If the left expr evals to false then seems it is always false for `AndExpr`.
I am still new to the codebase so not sure if there is any edge case here...

Return result if left expr eval to false in AndExpr

---

db.go
table.go
table_test.go

makes the index degree of the table configurable 
it can be set on the table config using the new method `WithIndexDegree(int)`
```golang
tableConfig := arcticdb.NewTableConfig(schema, 10, 512*1024*1024).WithIndexDegree(3)
```

 add configuration options for table

---

dynparquet/schema.go
granule.go
table.go
table_test.go

Moves column metadata up into the Granule layer. We maintain a list of min/max values for each column stored in a Granule. Then when iterating we can use the filter expr to determine if there's any valid data in the Granule, and skip reading it entirely if there isn't.

Filter whole granules during query

---

part_list.go
table_test.go

This fixes the issue detailed in #59 
We now iterate over all parts in a part list when the listType is None which happens during queries of the table.
It also fixes the unit test to wait for the txPool to drain instead of assuming we know how many tx the system has.

Fix 59 concurrency

---

query/engine.go
query/logicalplan/logicalplan.go
query/logicalplan/logicalplan_test.go

fixes issue in query/engine.go where the schema passed to the physical plan builder was hard-coded to the sample schema.
It now gets the schema from the logical plan. A new method was added to the logcal plan to return the schema which traverses the tree to get the schema from the TableProvider on either TableScan or SchemaScan steps.
A new method was also added to the TableReader interface which returns the schema

fix query schema not hard-coded

---

pqarrow/arrow.go

`array.Interface` is deprecated and removed by [this commit](https://github.com/apache/arrow/commit/61655b34f14e23fff217c314f60bbee92fe7961f).

Replace array.Interface with arrow.Array

---

dynparquet/example.go
pqarrow/arrow.go
table_test.go

This patch introduces minimum support for repeated types. Both parquet
and arrow organize repeated types in contiguous pages of values that
indicate whether they are null, a start of a list, or a part of a
started list, so this patch focuses on converting one layout to the
other.
cc @gotjosh

Add support for repeated types

---

aggregate_test.go
distinct_test.go
examples/simple.go
filter_test.go
table.go
table_test.go

Write cancellation. Addresses #54 
On context cancellation we'll mark all parts that have been written with a tombstone transaction id (`math.MaxUint64`) which causes them to be ignored during reads. They'll eventually be reaped during compaction and not be copied into the next granules.

Issue 54 abort writes

---

dynparquet/concat.go
dynparquet/example.go
dynparquet/nil_chunk.go
dynparquet/reader.go
dynparquet/reader_test.go
dynparquet/row.go
dynparquet/row_test.go
dynparquet/schema.go
dynparquet/schema_test.go
examples/simple.go
go.mod
go.sum
granule.go
pqarrow/arrow.go
table.go
table_test.go

parquet-go recently broke its APIs to give users more control over memory management and allow batch reads and writes for more control of performance.
cc @thorfour

Upgrade parquet-go

---

query/engine.go
query/logicalplan/builder.go
query/logicalplan/builder_test.go
query/logicalplan/logicalplan_test.go
query/logicalplan/optimize_test.go
query/logicalplan/validate.go
query/logicalplan/validate_test.go
query/physicalplan/physicalplan_test.go

related issue: https://github.com/polarsignals/arcticdb/issues/62 (Filtering by the wrong literal type causes a panic)
Added code that validates the logicalplan. We can use this as the place where we'll add more business logic in the future.
For now the current business rules are only for filters and they are:
- the plan must only have one field set as stated here: https://github.com/polarsignals/arcticdb/blob/main/query/logicalplan/logicalplan.go#L19
- the left side of a binary expression must be a column
- the column type must match what is being compared with it (e.g string compared w/ string, number compared w/ number)
It has some basic capability to print errors in a way that is somewhat human readable - for example:
```golang
(&Builder{}). …
```

WIP fix(62): Add validation of logicalplan

---

distinct_test.go
filter.go
query/engine.go
query/logicalplan/builder.go
query/logicalplan/builder_test.go
query/logicalplan/expr.go
query/logicalplan/logicalplan.go
query/logicalplan/optimize.go
query/logicalplan/optimize_test.go
query/logicalplan/validate.go
query/logicalplan/validate_test.go
query/physicalplan/aggregate.go
query/physicalplan/distinct.go
query/physicalplan/filter.go
query/physicalplan/project.go
table.go
table_test.go

Most importantly the `type Expr interface` now adds `json.Marshaler` & `json.Unmarshaler`.
For that, to work the structs implementing the `Expr` interface are now pointers.
A slight other improvement is the addition `DefaultOptimizers` wrapper, so it's easier to use in Parca and others.
In the future, it might be nice to use protobuf for sending the filters, but so far JSON was totally fine.

query/logicalplan: Add filter marshalling

---

table_test.go

This fixes the error with the `GranuleSplit` unit test reported in #71 
It was a matter of a non-deterministic split that was happening. If we just wait for the split before the final write we test the logic we're looking for.

Fix race cond

---

table.go

Hi, all! I think I found a race condition in the following snippet inside the `splitGranule()` method:
```golang
for {
curIndex := t.Index()
t.mtx.Lock()
index := curIndex.Clone() // TODO(THOR): we can't clone concurrently
t.mtx.Unlock()
deleted := index.Delete(granule)
if deleted == nil {
level.Error(t.logger).Log("msg", "failed to delete granule during split")
}
for _, g := range granules {
if dupe := index.ReplaceOrInsert(g); dupe != nil {
level.Error(t.logger).Log("duplicate insert performed")
}
}
// Point to the new index
if t.index.CAS(t.index.Load(), unsafe.Pointer(index)) {
sizeDiff := serBuf.ParquetFile().Size() - sizeBefore
t.size.Add(sizeDiff)
return
}
}
```
In particular, I replaced this check:
```golang
if t.index.CAS(t.index.Load(), unsafe.Pointer(index)) {
```
with the …

Fix index concurrency problem

---

table.go

If we start a new transaction, reads that started after the last
committed write, but before the compaction wont be able to find those commited
reads. Instead copy the watermark as the tx id to allow those reads to
be able to read all the committed data.
This is should be the fix for #71

Fix for concurrency race

---

granule.go
part.go
table.go

Move least of a part into a function. Lifted out all the calls in table where we fetched the least to use this helper function.
Also changed add part calls in addparttogranule to use the internal form that takes the least row so it doesn't need to be called again.
This addresses #86

part: added least func

---

filter.go
pqarrow/arrow.go
pqarrow/arrow_test.go
query/logicalplan/logicalplan.go
query/logicalplan/logicalplan_test.go
query/physicalplan/physicalplan.go
query/physicalplan/physicalplan_test.go
table.go
table_test.go

It's helpful to return the computed schema for a request. 
The `TableReader` now has an `ArrowSchema` method that under the hood uses the same `ParquetRowGroupToArrowRecord` function that's used to generate the Arrow Records that now additionally returns the schema belonging to those records.

TableReader returns ArrowSchema for request

---

examples/simple.go
pqarrow/convert/convert.go
pqarrow/convert/convert_test.go

I was playing with the sample code and thought it would be easier to debug if the log showed the type of parquet.Node.
I also thought that Int64 was appropriate for the StorageLayout of value in the sample code.

Add type to ParquetNodeToTypeWithWriterFunc log

---

pqarrow/convert/convert_test.go

This may be redundant, but it gives us an understanding of FrostDB's behavior and prevents changes like https://github.com/polarsignals/frostdb/pull/100.
Reference: https://github.com/segmentio/parquet-go/blob/edd371b528ffa7d9b637160d4fbd3b88f82698fa/type.go
Interestingly, JSON causes stack overflow, but I haven't looked into that yet.
```
=== RUN   TestParquetNodeToType
runtime: goroutine stack exceeds 1000000000-byte limit
runtime: sp=0xc0201f8388 stack=[0xc0201f8000, 0xc0401f8000]
fatal error: stack overflow
runtime stack:
runtime.throw({0x121ef33?, 0x1385f40?})
/usr/local/Cellar/go/1.18.3/libexec/src/runtime/panic.go:992 +0x71
runtime.newstack()
/usr/local/Cellar/go/1.18.3/libexec/src/runtime/stack.go:1101 +0x5cc
runtime.morestack() …
```

Add test cases in TestParquetNodeToType

---

table.go
table_test.go

This fixes the write benchmarks with new change in the code and some wrong expectations.
However running it seems  to show that we are missing data when running insert in parallel but not when we run sequentially.

Fixes write  benchmarks

---

dynparquet/concat.go
dynparquet/reader.go
dynparquet/row.go
dynparquet/row_test.go
dynparquet/schema.go
table_test.go

[`RowLessThan`](https://github.com/polarsignals/frostdb/blob/450025ff363cb7241d9a038dcaf74b8f2779f2ac/dynparquet/row.go#L40) is part of the hot path for ingestion.
This function was using `schema.Fields()` from parquet for each iterations which creates a new slice every-time but it's always the same.
This PR actually set it once for the schema and flows it down into the dynamic rows.
I've been running this in a dev cluster and it's gone from the profile, however there's still improvement require for this function, we need to find a way to cache sorting columns per dynamic rows.

Avoid allocations when asking for schema fields.

---

filter_test.go
query/logicalplan/optimize.go
query/logicalplan/optimize_test.go

If we have a projection that doesn't include all columns
in a filter, we skip the projection optimization to avoid
the projection removing those columns before the filter can
happen.
This addresses issue #114

Contionally add projection optimization

---

filter_test.go

Previously the filter tests never actually requested any data (as in no
data was projected), just for it to be filtered. This created confusing
result expectations in tests. This patch adds a projection to fix this.

filter_test.go: Add real projection to filter tests

---

query/logicalplan/expr.go

query: Allow recursive And expressions to be nil

---

db_test.go
distinct_test.go
filter.go
pqarrow/arrow.go
pqarrow/arrow_test.go
pqarrow/parquet.go
query/logicalplan/builder.go
query/logicalplan/builder_test.go
query/logicalplan/expr.go
query/logicalplan/logicalplan.go
query/logicalplan/logicalplan_test.go
query/logicalplan/optimize.go
query/logicalplan/optimize_test.go
query/physicalplan/aggregate.go
query/physicalplan/distinct.go
query/physicalplan/physicalplan.go
query/physicalplan/physicalplan_test.go
query/physicalplan/project.go
table.go
table_test.go

1) [Optimize distinct queries with single value per rowgroup](https://github.com/polarsignals/frostdb/commit/ce1959ed7e64d06d240400dd256315b49a546090):
Gathering distinct values of (non optional) dictionary encoded columns
is a constant operation per rowgroup when the dictionary only has a
single value. Additionally distinct projections using binary expressions
such as `timestamp > 0` can be determined without loading the row if the
column index has sufficient data. For example when the index notes that
all timestamps are between 5 and 8, then all values for `timestamp > 0`
are true, and therefore true for any distinct values in the rowgroup.
2) [pqarrow: Optimize distinct where all but one column are single value](https://github.com/polarsignals/frostdb/commit/872f3fcffed60a17989f579203c7 …

Optimize combined distinct queries

---

query/logicalplan/expr.go

Now that we have protobuf in various places in this repo I think we should replace all of this with protobuf ...

query/logicalplan: Fix expression unmarshaling

---

db_test.go

merging #142 and #141 caused the test to error since the query interface changed and the history wasn't linear

db_test.go: Fix conflict in query interface

---

dynparquet/nil_chunk.go
go.mod
go.sum

This PR adapts FrostDB to the changes introduced in https://github.com/segmentio/parquet-go/pull/289

update parquet-go: modify nilPage Data method to return encoding.Values

---

db.go
db_test.go
dynparquet/schema.go
pqarrow/arrow.go
pqarrow/arrow_test.go
query/logicalplan/builder.go
query/logicalplan/expr.go
query/physicalplan/aggregate.go
query/physicalplan/physicalplan.go
store.go
table.go

This obviates the need for the changes in #153 
- On `db.DB()` we'll now scan storage for table names, and open up read only tables for the discovered databases, allowing us to perform reads against those tables. 
- No longer use the table schema during queries, but instead use the row group schema
- on `db.Table()` if discovered we'll move a read only table into an active writable table

Use block schemas

---

filter.go
filter_test.go
query/logicalplan/expr.go
query/logicalplan/validate.go
query/physicalplan/filter.go

This change adds support for `Or` expressions, make changes to:
- `logicalplan`
- `physicalplan`
Also modifies the example to demonstrate it.
TODO:
Fixes #146

*: Add support for `Or` expressions

---

store.go
table.go

This addresses the memory spikes seen in #156 
Instead of accumulating the block in a memory buffer we write it directly to objstore using the io.Pipe.
In addition instead of performing `readRows` on all merged rowgroups which allocates a large buffer of memory to do so, we instead only merged subslices of the rowgroups.
Can see in the screenshot there's no longer a spike in memory as we write to storage

Unbuffered storage

---

store.go

We shouldn't return an error if there isn't one.

conditionally return no error

---

db.go
db_test.go

Don't register metrics until opening of the database is complete to avoid duplicate registration panic after an error has occurred.

Fix panic after error

---

aggregate_test.go
query/logicalplan/expr.go
query/logicalplan/validate.go
query/logicalplan/validate_test.go
query/physicalplan/aggregate.go

This commit adds an aggregate function to find the maximum value of an int64
column. This will be specifically useful to find the latest timestamp to query
over a range in a historical dataset in benchmarks.

logicalplan: add max aggregate function

---

bench_test.go

This commit adds three benchmarks that represent the queries run by Polar
Signals. The benchmarks are skipped by default and require a pre-generated
data directory for now.
Closes #151

*: add end-to-end benchmarks that represent polar signals query path

---

query/physicalplan/aggregate.go
query/physicalplan/distinct.go
query/physicalplan/filter.go
query/physicalplan/physicalplan.go
query/physicalplan/project.go

Adding the `Finish(context.Context) error` callbacks next.

query/physicalplan: PhysicalPlans are passed rather than just function callbacks

---

query/physicalplan/distinct.go
query/physicalplan/filter.go
query/physicalplan/physicalplan.go
query/physicalplan/project.go

As it has been done by @albertlockett, move the `Finish` callback to the PhysicalPlan interface.

query/physicalplan: Add finish callback to PhysicalPlan interface

---

query/physicalplan/aggregate.go
query/physicalplan/distinct.go
query/physicalplan/filter.go
query/physicalplan/physicalplan.go
query/physicalplan/project.go

This will add an attribute/log to the `PhysicalPlan/Build` span among the lines of:
```
TableScan - Projection (name,sample_type,sample_unit,period_type,period_unit,duration > 0) - Distinction (name,sample_type,sample_unit,period_type,period_unit,duration > 0)
```
```
TableScan - PredicateFilter ((name == goroutine AND (sample_type == goroutine AND (sample_unit == count AND (period_type == goroutine AND (period_unit == count AND (duration == 0 AND (timestamp > 1661951985385 AND timestamp < 1661952885385)))))))) - HashAggregate (value by labels,timestamp)
```

query/physicalplan: Add Diagram to draw physicalplan into traces

---

binaryscalarexpr.go
db_test.go
filter.go
query/logicalplan/logicalplan.go
query/logicalplan/logicalplan_test.go
query/physicalplan/physicalplan.go
query/physicalplan/physicalplan_test.go
store.go
table.go
table_test.go

In place of my previous PR with query hints.
This no longer has query hints, it instead using the query expr against the min/max values in a block from the parquet file metadata to determine if the block may contain data that satisfies the query.
This appeared to have the same effect as my previous PR but performs this in a more generic way as requested.

Filter blocks based on min/max values against query expr

---

binaryscalarexpr.go
granule.go
table.go

Removes the `filterGranule` function and instead leverages the Particulate work from https://github.com/polarsignals/frostdb/pull/170.
This allows us to use the filter on the Granule itself instead of having a custom function for it.

Fixup granule filters

---

db_test.go
pqarrow/arrow.go
pqarrow/arrow_test.go
pqarrow/convert/convert.go
pqarrow/writer/writer.go
table.go

Previously, in some cases, the Table.Iterator method would push Records with a
single row one at a time to the next operator. This would happen especially in
cases where a distinct optimization is executed and a single value is written
per parquet page. This commit changes the scan process to write scan results to
a provided RecordBuilder in order to buffer results up to a specified
builderBufferSize (default=1024) and take advantage of processing these results
in tight loops downstream.
The results are especially noticeable in QueryTypes, which takes advantage of
the aforementioned distinct optimizations:
```
QueryTypes-8     169ms ±11%      68ms ±13%  -59.43%  (p=0.000 n=10+9)
QueryMerge-8    27.0ms ±34%    23.4ms ±12%     ~     (p=0.095 …
```

pqarrow/frostdb: accumulate results in Iterator

---

pqarrow/arrow.go

On the distinct fast path, we were previously creating a dictionary from the
index value and then writing that dictionary's page for each page in a column
chunk.
This commit skips this unnecessary step and writes the single index value
directly to the writer. The code already checks that the index value is the
same across all pages, so only needs to be written once to the underlying
writer. This gives us a nice reduction in allocations, although it was mostly
an oversight on my part:
```
QueryTypes-8    42.5ms ±10%    40.7ms ± 6%     ~     (p=0.571 n=5+3)
name          old alloc/op   new alloc/op   delta
QueryTypes-8    80.6MB ± 0%    79.1MB ± 0%   -1.85%  (p=0.036 n=5+3)
name          old allocs/op  new allocs/op  delta
QueryTypes-8 …
```

pqarrow: avoid creating dictionary on distinct fast path

---

db.go
db_test.go
granule.go
table.go
table_test.go

This change is in lieu of https://github.com/polarsignals/frostdb/pull/179
While that change had a large amount of memory savings, it came at the cost of significantly decreased query performance due to having to open the parquet files every time. 
This change does two things:
1. Changes compaction:
granules are compacted based on their overall size in bytes from the parquet files they hold instead of raw number of rows. If however after a granule is compacted, its new size is less than that of the setting, it does not split the granule into two but instead replaces the previous granule with the new compacted one.
2. Uses a single writer during inserts instead of a writer per granule. 
```thor@thors-MacBook-Pro frostdb % benchstat before.txt 1mbgranule.txt
name …
```

Granule by size

---

db_test.go
query/logicalplan/logicalplan.go
query/logicalplan/logicalplan_test.go
query/physicalplan/physicalplan.go
query/physicalplan/physicalplan_test.go
table.go
table_test.go

All slices only have 1 entry which means no concurrency.
The Diagrams are currently broken, but I'll update them afterward. 
I think it makes sense to build a tree for those and use some sort of ASCI lib to print the tree.

Create array of PhysicalPlans to prepare for concurrency

---

db.go
dynparquet/nil_chunk.go
go.mod
go.sum
storage/bucket.go
store.go

The `io.Reader` interface does not guarantee that a Read will return the full requested set of bytes, but may instead return a subset of the request with no error. This was causing some problems with remote storage backends. 
This extends the `objstore.Bucket` interface with one that includes a `GetReaderAt` function that allows bucket implementations to read the remote parquet files.   
It also bumps the `parquet-go` version in frostDB to the latest that allows us to set read buffers size when opening parquet files to avoid many small reads.

Fix remote downloads

---

db.go
storage/bucket.go
store.go

We were erroneously wrapping the `storage.Bucket` with the `objstore.Bucket` which overrides and custom implementations provided.

wrap prefix bucket with a storage.Bucket prefixed bucker

---

distinct_test.go
pqarrow/arrow.go
table.go
table_test.go

This PR adds a struct that converts parquet rowgroups to arrow records. The conversion was previously stateless. With a struct, the door opens to a bunch of performance optimizations we can make, especially around avoiding redoing work for reach row group. In this PR, two optimizations are implemented:
- Reusing writers across row groups (only instantiated on row group schema change)
- Calculating index mappings upfront (on a row group schema change)
```
QueryTypes-8    11.5ms ± 1%     5.3ms ± 1%  -53.78%  (p=0.008 n=5+5)
QueryMerge-8    19.5ms ± 0%    18.7ms ± 0%   -3.84%  (p=0.008 n=5+5)
QueryRange-8    12.5ms ±18%    11.3ms ± 2%   -9.42%  (p=0.016 n=5+4)
name          old alloc/op   new alloc/op   delta
QueryTypes-8    88.1MB ± 0% …
```

pqarrow: add ParquetConverter

---

dynparquet/nil_chunk.go
dynparquet/schema.go
go.mod
go.sum
table.go

This should alleviate our CI flakes where too many goroutines are alive at one
time.
There is also a fix pulled in for buffering bloom filter reads.

*: update parquet-go to include goroutine leak fix

---

db_test.go
dynparquet/example.go
examples/simple.go
table.go

This adds a layer on top of the `Insert` API to increase accessibility of the API. The new API function is `Write(context.Context, ...any)` where a user may write a normal Go struct and FrostDB will handle converting it into a parquet buffer.
I had taken a first pass at this some time ago in https://github.com/polarsignals/frostdb/pull/67/files but finally got around to cleaning that up and making it even more ergonomic.
While I'm certain this does not cover every type of struct that someone may want to write, it covers the use cases that exist in FrostDB today, and can be expanded overtime to support more fields as required.

table: Write api to make FrostDB easier to use

---

granule.go
table.go

Since changing the way we compact granules in https://github.com/polarsignals/frostdb/pull/189 it's less obvious that granule level filtering is valuable due to the reduction in the number of granules.
Granule level filtering also added locking and has a current outstanding bug https://github.com/polarsignals/frostdb/issues/188
I propose that we remove the granule level filtering, and can add it back in the future should a need arise.
```
thor@thors-MacBook-Pro frostdb % benchstat before.txt after.txt
name                                          old time/op    new time/op    delta
QueryTypes-10                                   5.16ms ± 0%    4.88ms ± 0%   ~     (p=1.000 n=1+1)
QueryMerge-10                                   22.2ms ± 0%    21.7ms ± 0%   ~     (p=1.000 n=1+1) …
```

remove min/maxes from granule metadata

---

binaryscalarexpr.go
granule.go
store.go
table.go
table_test.go

Introduces a table level option of `WithRowGroupSize` which informs the writer when to `Flush()` the buffer and write out a RowGroup. 
It uses this setting both during granule compaction, as well as block persistence.

Fix writer partition

---

pqarrow/arrow.go
pqarrow/arrow_test.go
pqarrow/builder/listbuilder.go
pqarrow/builder/optbuilders.go
pqarrow/builder/recordbuilder.go
pqarrow/convert/convert.go
pqarrow/writer/writer.go

This PR adds the concept of optimized builders to FrostDB. These are array.Builders that can build arrow arrays more efficiently than the default builders by only copying when necessary. This is especially important when handling data like variable-sized strings, where we'd go through the following process:
- Read parquet strings stored in flat format, create a two-dimensional slice of values representing these.
- Append values to an arrow builder, which reads each string and converts it back to flat format.
With the new builder, we can immediately just copy the flat data + offsets and cast them to an arrow array when necessary. The improvements are noticeable especially in QueryRange:
```
QueryTypes-8    3.84ms ± 3%    3.79ms ± 3%     ~ …
```

pqarrow/builder: optimize Parquet to Arrow conversion

---

aggregate_test.go
bench_test.go
compaction.go
compaction_test.go
db.go
db_test.go
granule.go
table.go
table_test.go

This commit adds a worker pool of goroutines (`runtime.NumCPU` by default) per database that will iterate over all the tables in that database and attempt to perform a compaction every defined sweep interval (`100ms` by default).
The compaction logic has not been modified.
This PR also adds a `compacting` atomic boolean to the granule so that no two goroutines attempt to compact the same granule. Previously, I think this was the case because the only atomic that was checked was `pruned`, which is only set once the granule has been pruned from the index.
Closes #119

frostdb: add compactorPool to limit compaction goroutines

---

compaction.go
compaction_test.go
db.go
dynparquet/row.go
dynparquet/schema.go
granule.go
part.go
table.go

This PR implements simple leveled compaction of parts into level 1 parts as described in #223, which are guaranteed to never be overlapping. This will hopefully improve our memory usage during compactions and avoid the spikes we've seen in our clusters. Please refer to the individual commits for details. I've tried to split it up into 1) The addition of leveled compaction, 2) Handling out-of-order inserts which should only happen very rarely but it is an edge case we need to handle.

frostdb: add leveled compaction

---

db.go
table.go

This change
- prevents further writes from happening after a table has been closed.
- adds a histogram to record how long it takes a database to shutdown.
- shuts down databases concurrently

Stop writes on close

---

db_test.go
pqarrow/arrow.go
pqarrow/arrow_test.go
pqarrow/builder/recordbuilder.go
query/logicalplan/logicalplan.go
query/logicalplan/logicalplan_test.go
query/physicalplan/physicalplan.go
query/physicalplan/physicalplan_test.go
table.go
table_test.go

This addresses issue #230 by removing the `ArrowSchema` call in the physical plan execute function. It instead builds the output schema as it converts row groups. 
Benchmark with simulated network latency to storage
```
name                      old time/op    new time/op    delta
PersistentQuery/Types-10     638ms ± 2%     317ms ± 2%  -50.32%  (p=0.000 n=29+28)
PersistentQuery/Merge-10     2.51s ± 3%     2.22s ± 3%  -11.61%  (p=0.000 n=29+28)
PersistentQuery/Range-10     877ms ± 2%     562ms ± 3%  -35.91%  (p=0.000 n=30+28)
name                      old alloc/op   new alloc/op   delta
PersistentQuery/Types-10    68.3MB ± 0%    36.7MB ± 0%  -46.36%  (p=0.000 n=29+30)
PersistentQuery/Merge-10    32.0GB ± 3%    32.0GB ± 1%     ~     (p=0.296 n=30+28)
PersistentQuery/Range-10    2.43GB ± 1% …
```

dynamically build the output schema

---

pqarrow/arrow.go
table.go
table_test.go

Previously we've been ignoring the RowGroups that had no data for the queried labels, aka no fields, but since the refactor in #247 we haven't been doing that and it panicked. 
Now, going forward we'll simply ignore those RowGroups again. 
Seems to work just fine again locally with the parca-agent ingesting and parca-load querying. 
Closes https://github.com/parca-dev/parca/issues/2111

Ignore RowGroups that don't have data when converting

---

compaction.go
dynparquet/reader.go

Inspired by @thorfour's recent changes to our cloud product to use a MultiRowGroup to wrap multiple sorted row groups in a single row group, this change does the same for compaction in FrostDB.
The idea is to reduce the number of decompressed pages held in memory at any one time, which should drastically reduce memory usage. Given that we know that all row groups within a part are sorted, exposing a part as a single row group lets us have one cursor per part instead of one cursor per row group per part.

frostdb: use parquet.MultiRowGroup to reduce compaction memory usage

---

aggregate_test.go
query/logicalplan/expr.go
query/logicalplan/optimize.go
query/physicalplan/project.go

This updates the query engine to support two things:
- BinaryExpr Projections of Aggregation columns
- Alias of BinaryExpr projections
ex:
```
Aggregate(
logicalplan.Sum(logicalplan.Col("value")),
logicalplan.DynCol("labels"),
logicalplan.Col("timestamp"),
).
Project(
logicalplan.Col(logicalplan.Sum(logicalplan.Col("value")).Name()),
logicalplan.DynCol("labels"),
logicalplan.Col("timestamp").Gt(logicalplan.Literal(1)).Alias("timestamp"),
).
```
Where we project the timestamp column from the aggregation to a `timestamp > 1` column and then rename that column to `timestamp`

Aggregation projection

---

db.go
tx_list.go
tx_list_test.go

In an attempt to address https://github.com/polarsignals/frostdb/issues/246 I've rewritten the tx list to be a [Harris style ordered linked-list](https://timharris.uk/papers/2001-disc.pdf). I originally wrote the list using pointer arithmetic (shame on me) but Go's race detector screamed at me, so I changed it to use `nil` pointers and save off the original pointer in a separate atomic.Pointer.
Ordering the linked list means we no longer need to perform a periodic sweep because the ordering of the completed transactions means we only need to iterate until we encounter a tx that isn't next in line. Furthermore this fixed a race condition that was present with the deletion routine that could cause transactions to go missing which would cause the list to be permanently hung.
``` …
```

Sorted tx pool

---

dynparquet/schema.go
go.mod
go.sum
pqarrow/convert/convert_test.go

I think previously the only thing that was wrong was our usage ... we never called `.Close()`, which caused the goroutine opened by `.Rows()` to leak.
Roughly ~30% of the ingest path of Parca/Polar Signals Cloud is spent in this code, so hopefully this improves that.

dynparquet: Use parquet-go's copy rows

---

pqarrow/builder/optbuilders.go
pqarrow/builder/recordbuilder.go
pqarrow/builder/utils.go
query/physicalplan/aggregate.go
query/physicalplan/distinct.go

Ran into reorganizing this code while working on the ordered aggregator.
```
benchstat bmain bopt
name           old time/op    new time/op    delta
Query/Types-8    8.31ms ± 3%    7.79ms ± 1%   -6.28%  (p=0.000 n=10+9)
Query/Merge-8    18.9ms ± 4%    15.6ms ± 2%  -17.42%  (p=0.000 n=9+10)
Query/Range-8    6.29ms ± 1%    6.34ms ± 1%   +0.74%  (p=0.006 n=9+9)
name           old alloc/op   new alloc/op   delta
Query/Types-8    51.5MB ± 0%    52.1MB ± 0%   +1.09%  (p=0.000 n=10+10)
Query/Merge-8     101MB ± 0%      92MB ± 0%   -9.24%  (p=0.000 n=9+10)
Query/Range-8    24.9MB ± 0%    24.5MB ± 0%   -1.39%  (p=0.000 n=10+10)
name           old allocs/op  new allocs/op  delta
Query/Types-8     45.5k ± 0%     45.5k ± 0%   -0.19%  (p=0.000 n=10+10)
Query/Merge-8      205k ± 0%      169k ± 0% …
```

physicalplan: switch Distinct and HashAggregate to use optimized builders

---

aggregate_test.go
logictest/testdata/aggregate/window
query/logicalplan/expr.go
query/physicalplan/aggregate.go
sqlparse/visitor.go

We want to be able to group aggregations into interval/duration buckets.
A simple example in English would be: Sum up all messages in a chat by the minutes in an hour.
More technically correct is the logical test in `logictest/testdata/aggregate/window`. 
For this, to work we exploit the fact that we can group timestamps into intervals by dividing these through the duration.
| timestamp 	| duration 	| math       	| hashed bucket 	|
|-----------	|----------	|------------	|---------------	|
| 0         	| 2        	| floor(0/2) 	| 0             	|
| 1         	| 2        	| floor(1/2) 	| 0             	|
| 2         	| 2        	| floor(2/2) 	| 1             	|
| 3         	| 2        	| floor(3/2) 	| 1             	|
| 4         	| 2        	| floor(4/2) 	| 2             	|
| 5         	| …

Allow aggregations to be grouped by durations

---

dynparquet/schema.go
go.mod
go.sum

This adds a bunch of recent performance and memory improvements. Notable ones are:
https://github.com/segmentio/parquet-go/pull/434
https://github.com/segmentio/parquet-go/pull/435
https://github.com/segmentio/parquet-go/pull/436

deps: update parquet to 3f277a9

---

pqarrow/builder/optbuilders.go
pqarrow/builder/optbuilders_test.go
query/physicalplan/aggregate.go
query/physicalplan/distinct.go

Fixes #270 
This PR also adds the optimized builders back into the hash aggregate and distinct given they were removed until the issue was resolved.

builder: append offset when appending NULL in OptBinaryBuilder

---

pqarrow/builder/optbuilders.go
pqarrow/builder/optbuilders_test.go

This was broken in all optimized builders. Also added a test.

pqarrow: fix RepeatLastValue

---

query/physicalplan/ordered_aggregate.go
query/physicalplan/ordered_aggregate_test.go

This commit supports grouping by multiple columns in ordered aggregations. It implements this using a min-heap of group ranges so that the first group by value to differ in any column is considered the start of a new group.
This commit also adds a TestOrderedAggregate unit test that creates and pushes arrow records to the ordered aggregate.

physicalplan: support muliple group by columns in the OrderedAggregate

---

aggregate_test.go
bench_test.go
logictest/testdata/aggregate/aggregate
logictest/testdata/aggregate/aggregate_nulls
logictest/testdata/aggregate/window
query/engine.go
query/logicalplan/builder.go
query/logicalplan/builder_test.go
query/logicalplan/logicalplan.go
query/logicalplan/logicalplan_test.go
query/logicalplan/optimize.go
query/logicalplan/optimize_test.go
query/logicalplan/validate.go
query/logicalplan/validate_test.go
query/physicalplan/aggregate.go
query/physicalplan/physicalplan_test.go
sqlparse/visitor.go

FrostDB should be able to accept queries like:
```
select sum(value), count(value), max(value) group by labels.label2
select sum(value) as value_sum, count(value) as value_count group by second(3)
```
For this, to work FrostDB needs to accept multiple aggregations within a single query. 
FrostDBs Aggregate interface has to be updated:
```diff
-Aggregate(aggExpr logicalplan.Expr, groupExprs ...logicalplan.Expr) Builder
+Aggregate(aggExpr, groupExprs []logicalplan.Expr) Builder
```
To make our lives easier to figure out all the things that belong to a single column that's being aggregated, I've introduced `AggregateColumn`. 
Benchmarks show no significant impact:
```
name                  old time/op    new time/op    delta
Aggregation/sum-24      1.84ms ± 3%    1.87ms ± 1%    ~ …
```

Accept multiple aggregations within a single query

---

pqarrow/arrowutils/merge.go
pqarrow/arrowutils/merge_test.go
pqarrow/arrowutils/utils.go
pqarrow/builder/optbuilders_test.go
pqarrow/builder/utils.go
query/physicalplan/ordered_aggregate.go

This PR introduces a way to merge two sorted arrow records according to given sorting columns.
I also have a change on the back burner to drop duplicates/call a callback on equal values, but it's not working given I assumed some incorrect things about `container/heap`. I think the best thing will be to merge this without special duplicate behavior and then see how we use it in the ordered aggregator.

arrowutils: introduce arrow utility package and MergeRecords

---

logictest/testdata/aggregate/window
query/physicalplan/aggregate.go

In case of a query like `select count(timestamp) as timestamp_count group by second(3)` we have to add the `timestamp` column arrays once to the `columnToAggregate` with the way it was rewritten the column was added twice. 
In the end `columnToAggregate` had the timestamp column twice and return `aggregate field not found, aggregations are not possible without it` as error.

query/physicalplan: Fix aggregations for columns that are grouped by

---

compaction.go
compaction_test.go
table_test.go

This call would simply verify that we placed the cursor at the desired row. However, this SeekToRow is causing correctness issues although it's supposed to be a noop.
Fixes #294

frostdb: remove unnecessary SeekToRow call during compaction

---

dynparquet/reader.go

This was unnecessary and more expensive.

dynparquet: avoid creating a reader when calling SerializedBuffer.NumRows

---

aggregate_test.go
logictest/testdata/aggregate/aggregate
query/logicalplan/expr.go
query/logicalplan/optimize.go
query/physicalplan/project.go
sqlparse/visitor.go

Thanks to @asubiotto we had the idea to make the average aggregation a projection. 
The way it works now is that the logical plan creates an average aggregation but then optimizes those into the two `sum` and `count` aggregations plus an `avg` projection. The logical plan makes sure to wrap both aggregations with the average projection, such that anything reading the column afterward will only see the final result. 
TODO:
Closes #177 
Superseeds #266 & #190

Add support for average aggregations

---

query/physicalplan/main_test.go
query/physicalplan/ordered_synchronizer.go
query/physicalplan/ordered_synchronizer_test.go

This commit adds an OrderedSynchronizer component that merges ordered records
pushed from many concurrent inputs and pushes the merged record to a single
output.
The strategy this commit implements is to block the inputs until all inputs
have pushed a record. This is the most straightforward strategy since the other
option is to store the pushed records, but that requires copying all data which
might be more expensive.

physicalplan: add OrderedSynchronizer

---

pqarrow/arrowutils/groupranges.go
pqarrow/arrowutils/merge.go
pqarrow/arrowutils/utils.go
query/physicalplan/aggregate.go
query/physicalplan/ordered_aggregate.go
query/physicalplan/ordered_aggregate_test.go

This PR adds the missing partial ordering support to the OrderedAggregate.
Instead of returning a record on each call to Callback as was previously done,
the OrderedAggregate now buffers the aggregation results and groups for each
ordered set and then merges the results on Finish.
A bunch of incidental bugfixes and test flake fixes have also been included. The first couple of commits also introduce some helper code used by the last (main) commit.
Closes #287 
The ordered aggregate is still not ready for production usage since it doesn't handle columns appearing/disappearing from the input. However, I want to take a different approach (starting down the static schema route I mentioned) to solve this, so would rather merge a complete working version (at least from the unit test perspective) …

physicalplan: add partial ordering support do the OrderedAggregate 

---

dynparquet/schema.go
logictest/logic_test.go
logictest/testdata/exec/aggregate/ordered_aggregate
logictest/testdata/plan/aggregate/aggregate
query/engine.go
query/physicalplan/aggregate.go
query/physicalplan/ordered_aggregate.go
query/physicalplan/ordered_synchronizer.go
query/physicalplan/ordered_synchronizer_test.go
query/physicalplan/physicalplan.go
query/physicalplan/planordering.go

This PR is a bunch of commits with fixes and planning changes in order to plan ordered aggregations when the grouping columns are a prefix of ordering columns. This includes cases in which a filter "covers" a prefix of the ordering columns up to the group columns (e.g. when the order is "name, labels, timestamp" and we filter name="somename" and group by (labels,timestamp)). For more explicit information on what cases are and aren't covered, please refer to the `plan/aggregate` logic test which goes into more detail.
Ordered aggregations are disabled by default and can be enabled (as is done with logic tests) by calling `query.NewEngine` and adding the `WithOrderedAggregations` option given that there are most likely some latent bugs.
The performance improvement over hash aggregates is …

physicalplan: plan ordered aggregations

---

wal/wal.go

tidwall/wal can refuse to write a batch due to out of order indexes, but it's hard to tell the underlying cause just from the error message. Printing the batch that we attempted to write will help diagnosing the cause. The log message will be very verbose, but since it is only logged on error, that should be fine.

wal: add batch to log message when encountering write error

---

bufutils/dyncols.go
compaction.go
compaction_test.go
db_test.go
dynparquet/example.go
dynparquet/row.go
dynparquet/schema.go
go.mod
granule.go
parts/part.go
pqarrow/arrow.go
pqarrow/arrow_test.go
pqarrow/parquet.go
store.go
table.go
table_test.go

This adds support to ingest Arrow records directly into FrostDB. It **does not** deprecate the previous method of ingesting parquet buffers directly. That may be a future PR to deprecate that write path. 
It stores arrow records inside the `Part` object, where a part may now hold either a parquet buffer or an arrow record. 
Things that are **not** implemented in this PR that should be implemented in follow-on PRs:
- WAL support (writing the wal with arrow records is not supported at this time)
- Nested schema support 
- Dictionary arrays. (We want this to reduce the memory overhead of storing arrow records)

Arrow record ingestion support

---

db.go

This is an idea for #317 
Sadly the bytes on the heap read from the runtime don't seem to significantly improve with this approach. :thinking: 
_This chart shows the memory heap in bytes every 128 inserts_

Unblock compaction by setting tx during WAL replay

---

db_test.go
query/logicalplan/logicalplan.go
query/logicalplan/logicalplan_test.go
query/physicalplan/physicalplan.go
query/physicalplan/physicalplan_test.go
table.go
table_test.go

Refactored the `IterOptions` in the table interface to consume the option pattern to prevent having to pass empty structs for lots of unit testing.

use option pattern for iteropts

---

.golangci.yml
logictest/runner.go
pqarrow/arrow.go
pqarrow/convert/convert.go
query/logicalplan/optimize.go
query/logicalplan/validate.go
query/physicalplan/aggregate.go
query/physicalplan/binaryscalarexpr.go
sqlparse/visitor.go
table_test.go
tx_list.go
wal/wal.go

This PR fixes all the lint issues reported by golangci-lint that have creeped into the codebase over time as well as ignoring lint issues that would take too long to fix.
My idea is to make passing golangci-lint a required step before merging, otherwise there doesn't seem to be much use in having a linter.

*: fix all lint issues

---

query/physicalplan/physicalplan.go
table.go

By default, `runtime.GOMAXPROCS(0)` returns the same value as `runtime.NumCPU()`, but it will allow the user to configure the concurrency with the `GOMAXPROCS` environment variable (and potentially [go.uber.org/automaxprocs](https://pkg.go.dev/go.uber.org/automaxprocs) to follow the cgroup limit)
This unifies the handling of the concurrency value in FrostDB where half the code base was already doing so:
```console
$ rg GOMAXPROCS
compaction.go
37:             concurrency: runtime.GOMAXPROCS(0),
query/physicalplan/physicalplan.go
19:var concurrencyHardcoded = runtime.GOMAXPROCS(0)
table.go
95:             blockReaderLimit: runtime.GOMAXPROCS(0),
db.go
211:    errg.SetLimit(runtime.GOMAXPROCS(0))
```

concurrency: Use GOMAXPROCS instead of NumCPU

---

dynparquet/row.go
dynparquet/row_test.go

When comparing two rows, the comparison code needs to merge the dynamic columns found in each row and create a copy of each row with the union of both dynamic column sets. These new row values were previously created in the same order as the sorting column names. However parquet assigns column indexes to each column name and this index does not necessarily correspond to the index into the slice of sorting columns. Therefore, the parquet comparison code could compare a value at an incorrect column index.
This commit iterates over the merged schema so that parquet comparison code lookups work successfully.

dynparquet: create comparison rows according to sorting schema

---

dynparquet/schema.go
go.mod
go.sum

This update importantly pulls in fixes to null sorting. FrostDB does not use this directly, but exposes an API that does.

deps: update parquet to 1d85e8136681

---

db_test.go
table_test.go
wal/wal_test.go

A lot of tests would create temporary directories and then clean them up, or do so and forget to (e.g. filesystem.NewBucket). This commit switches all these instances to use t.TempDir() which takes care of all the directory creation/cleanup for tests and returns the path.

*: remove manual creation of directories in tests

---

dynparquet/row.go
table.go
table_test.go

Previously in the insert path, the rows to insert were iterated over once to determine the granule that each row belonged to and a second time to perform the insert. This commit improves performance by reading all the rows to insert once.
```
name            old time/op    new time/op    delta
InsertSimple-8    17.0ms ± 2%    15.1ms ± 2%  -11.15%  (p=0.000 n=10+10)
name            old alloc/op   new alloc/op   delta
InsertSimple-8    16.6MB ± 0%    13.5MB ± 1%  -18.51%  (p=0.000 n=10+10)
name            old allocs/op  new allocs/op  delta
InsertSimple-8      156k ± 0%      151k ± 0%   -3.23%  (p=0.000 n=10+10)
```

*: improve insert performance

---

bench_test.go
dynparquet/schema.go

This was a hot path during WAL replay. Computing the full name only once
provides an improvement when replaying production WALs:
```
name      old time/op    new time/op    delta
Replay-8     32.3s ± 2%     28.1s ± 9%  -13.02%  (p=0.000 n=9+10)
name      old alloc/op   new alloc/op   delta
Replay-8    81.5GB ± 1%    75.1GB ± 2%   -7.79%  (p=0.000 n=9+10)
name      old allocs/op  new allocs/op  delta
Replay-8      704M ± 2%      532M ± 4%  -24.51%  (p=0.000 n=9+10)
```

dynparquet: don't recompute dynamic column full name

---

dynparquet/schema.go
table.go

Rows read using ReadRows are not safe to reuse after a subsequent call to ReadRows. This commit changes calls to either use the rows right after the ReadRows call or calls Clone on the rows. Calling Clone has a slight perf hit on simple insert benchmarks:
```
name            old time/op    new time/op    delta
InsertSimple-8    15.7ms ± 1%    16.3ms ± 2%  +3.84%  (p=0.000 n=9+10)
name            old alloc/op   new alloc/op   delta
InsertSimple-8    13.5MB ± 1%    14.2MB ± 1%  +5.25%  (p=0.000 n=10+10)
name            old allocs/op  new allocs/op  delta
InsertSimple-8      150k ± 0%      164k ± 0%  +9.35%  (p=0.000 n=10+10)
```
But improves things when replaying a production WAL.
```
name      old time/op    new time/op    delta
Replay-8     65.6s ± 3%     60.6s ± 2%  -7.68%  (p=0.008 …
```

*: fix ReadRows usage

---

db.go

This allows consumers of FrostDB to utilze things like errors.Is(err, ErrTableNotFound{TableName: "my_table"})

Expose table name in table not found error

---

wal/wal.go

This should be super helpful when troubleshooting WAL replays. 
The `"path"` plus `"first_index"` should guide one directly to the corrupted file.
We still fail hard after recovering. We just have more context now.

wal: Recover panic when replaying WAL to print more context

---

query/engine.go
query/physicalplan/physicalplan.go

This will mostly likely occur in a distributed storage fashion and is less likely for Parca itself.

query: Return error if schema is nil after building physical plan

---

binaryscalarexpr.go
binaryscalarexpr_test.go

The Min/Max functions could panic with 
```
panic: unsupported value comparison: Type(?) [recovered]
panic: unsupported value comparison: Type(?)
goroutine 5 [running]:
testing.tRunner.func1.2({0x102a34080, 0x1400033b990})
/usr/local/go/src/testing/testing.go:1396 +0x1c8
testing.tRunner.func1()
/usr/local/go/src/testing/testing.go:1399 +0x378
panic({0x102a34080, 0x1400033b990})
/usr/local/go/src/runtime/panic.go:884 +0x204
github.com/polarsignals/frostdb.compare({0x0, 0x0, 0x0, 0x0, 0x0, 0x0}, {0x0, 0x0, 0x0, 0x0, ...})
/Users/thor/go/src/github.com/polarsignals/frostdb/binaryscalarexpr.go:151 +0x320
```
When a column chunk had all null values. This adds a check to those functions to properly handle a empty column chunk.

Fix panic on nil cols

---

db_test.go
query/physicalplan/aggregate.go
query/physicalplan/ordered_aggregate.go
query/physicalplan/ordered_aggregate_test.go
query/physicalplan/physicalplan.go

Performs an aggregation read on a read only table. Aggregations require a schema, and this causes a panic as read only tables do not have a schema set.

unit test: read only table queries

---

db.go

As discussed we want to have some more insight into replaying WAL that's not super detailed debug logs but when it starts and stops.
```
...
level=info db=parca name=parca ts=2023-03-07T12:46:12.961225674Z caller=db.go:397 msg="replaying WAL"
level=info db=parca name=parca ts=2023-03-07T12:46:26.226864676Z caller=db.go:564 msg="replaying WAL completed" duration=13.265576152s
...
```

Add info logs for starting and finishing WAL replays

---

bench_test.go
compaction.go
dynparquet/schema.go
table.go

This updates the `Serialize` function 
Previously we were collecting all row groups in the entire table block, and using the parquet merge function to merge all the row groups into a single row group. This causes a large memory spike because we would load at least a page for every row group (or maybe 2 if we're async reading the pages) into memory to perform the heap sort of all the row groups.
Instead of doing that; we can leverage the fact that Granules are already sorted in relation to each other and instead merge each Granules row groups into a single one, and write that directly to the final file. The benchmark shows some considerable gains in memory, and speed.
```
thor@thors-MacBook-Pro frostdb % benchstat before.txt after.txt
name           old time/op    new time/op    delta …
```

Serialize less memory

---

db.go
db_test.go
snapshot.go
table.go

From the snapshot design document:
Snapshot recovery in the presence of block rotations can be subtle. The situation we want to avoid is recovering from a snapshot that has data from a table block that has been rotated (i.e. persisted). If the aforementioned [snapshot intervals](#interval) and [recovery](#recovery) algorithms are followed without triggering a snapshot on block rotation, it is possible to load a snapshot at txn `n` when a block rotation happened at txn `n+k`. When serving queries, FrostDB could return duplicate data for writes with txn ids `<= n` since the same row could be both in-memory (originating from the snapshot) and in block storage (previously persisted).  Triggering snapshots on block rotation will not include the rotated block. When the snapshot is loaded during …

frostdb: add snapshot on block rotation

---

dynparquet/example.go
table.go
table_test.go

The `rowWriter` had been writing row groups in a "fuzzy" manner, in that if you passed a set of rows that exceeded the row group size, it would write them all into the current row group.
This fixes that fuzziness by correctly truncating the row group to only include the specified number of rows.

Enforce row group size

---

bench_test.go
db.go
db_test.go
snapshot_test.go
table.go
wal/wal.go
wal/wal_test.go

In efforts to make the WAL/replay more robust I've added two things here:
- On wal read panics instead of continuing the panic we instead truncate the WAL up to the last good tx. Using some corrupted wals from production this works really well.
- On DB open (and wal open) replay the WAL. This is mostly a refactor, but it does remove some weird footguns where you could open a DB with a WAL and not replay it, or write to it while you were replaying it.
Closes #328

Replay wal on open

---

db.go
db_test.go

This commit deletes the snapshot dir alongside the wal dir if blocks are successfully persisted on Close. Not doing so could cause a recovery from this state to never log to the WAL since the recovered db tx from the snapshot could be much higher than the new WAL's last index.
Additionally, this commit enhances recovery testing with other scenarios.

*: fix not deleting snapshot dir on db.Close

---

db.go
db_test.go
snapshot_test.go

Close expects some fields to be non-nil (e.g. metrics when triggering a snapshot on close), so this commit introduces a lighter-weight closeInternal that is called on a db setup error, which is all that is needed. Not doing so was causing a nil pointer exception.

*: call closeInternal on db startup error rather than Close

---

binaryscalarexpr.go
logictest/testdata/exec/filter/filter_projection
query/physicalplan/binaryscalarexpr.go

Closes #394 
So I don't think we actually need to project the null column here to solve this problem, we just actually needed to handle the missing column case during binary scalar expression evaluations.

394 project null columns

---

compaction.go
granule.go

New granules is concurrently accessed, it's written by the compaction routine, and it's accessed by both reads and writes to propagate after compactions. 
Due to this it should be an atomic pointer so that access is thread safe.

new granules atomic pointer

---

cmd/parquet-tool/main.go

This commit modifies parquet-tool to also print an `Encoding` column in the output table for a parquet file.

parquet-tool: Print column encoding

---

pqarrow/parquet.go

We weren't handling null entries in dictionaries correctly when constructing rows from arrow records

fix arrow row conversion panic on nil dictionaries

---

db.go
db_test.go
filter.go
pqarrow/arrow.go
query/logicalplan/builder.go
query/logicalplan/expr.go
query/logicalplan/validate.go
query/physicalplan/aggregate.go
query/physicalplan/filter.go
query/physicalplan/planordering.go
store.go
table.go
table_test.go

This replaces the objstore bucket interface with a slightly more specific interface for remote storage called sources and sinks. 
This allows pluggable sources/sinks for remote storage for FrostDB to write and read to/from. This allows us to remove the "ignoreObjstoreOnQuery" flag and instead one could simply configure a sink but not a source to achieve the same goal. The separate set of sources and sinks allows for a more flexible system where one could perform migrations from old storage by configuring a new sink but keep a previous source to continue to read from.
I've also updated the Visitor pattern interface to include an in-order visitor.

Data sources and sinks

---

.github/workflows/go.yml
.github/workflows/golangci-lint.yml
bench_test.go

This sub-benchmark runs within the BenchmarkQuery setup to measure how fast a simple filter runs. B/msec are also reported, which is something that we're tracking in our OKRs (i.e. scan layer throughput). These bytes are measured as total block size, so if we discard scanning granules, that counts as processing that granule which is nice because it captures how well we're doing in scan layer filtering before parquet conversion.

bench: add BenchmarkQuery/Filter

---

db.go
db_test.go
wal/wal.go

Previously, db.Close would call os.RemoveAll on the snapshots and wal
directories. This is an O(n) operation, which could lead to some leftover
files if we exceed the graceful shutdown period.
This commit changes the removal to move both directories to a trash/ directory,
which is an O(1) operation. This trash/ directory can be removed safely on
startup if it still exists.
Additionally, this commit moves closeInternal to before removing the
directories. This ensures that the WAL is flushed and closed before deletion.

db: move snapshots and wal directories to trash

---

compaction_test.go
db_test.go
dynparquet/row.go
dynparquet/schema.go
parts/part.go
pqarrow/parquet.go
table.go
table_test.go

This PR is the result of a Let's Profile stream where we looked at CPU usage in the frostdb ingestion path. The changes improve insertion benchmarks by ~50%.
The only thing I'm not quite sure about is that the third commit release pooled `parquet.Schema`s with a potential use after a release (e.g. storing the schema somewhere). I *think* this is fine because schemas are immutable once created, but it would be nice to have someone else's opinion.

dynparquet: reduce allocations

---

parts/part.go
pqarrow/parquet.go
table.go

This function was unnecessary since callers can get dynamic columns from the record and request a pooled parquet schema with these. This commit should reduce allocations and CPU time in the ingestion path.

pqarrow: remove RecordToDynamicSchema

---

pqarrow/arrow_test.go
pqarrow/arrowutils/arrow.go
pqarrow/builder/listbuilder.go
pqarrow/builder/optbuilders_test.go
pqarrow/builder/utils.go
pqarrow/convert/convert.go
pqarrow/convert/convert_test.go
pqarrow/parquet.go
pqarrow/writer/writer.go
query/physicalplan/aggregate.go
query/physicalplan/binaryscalarexpr.go

This reverts commit c236424d87e62b753883f42180c86319aa69a881.
Turns out the slicing bug was only fixed on regular lists, not large lists. Reverting until we can use large lists.

Revert "Use a large list insted of a normal list (#449)"

---

logictest/logic_test.go
logictest/runner.go

In addition to running the logic tests with Parquet insertions we now also run the tests with arrow insertion

run all logic tests as arrow

---

bench_test.go
pqarrow/arrowutils/groupranges.go
pqarrow/arrowutils/utils.go
pqarrow/builder/optbuilders_test.go
query/physicalplan/ordered_aggregate.go

Since moving to arrow v12 we can use some of the new helper functions that library provides.

replace GetValue helper function with new GetOneForMarshal

---

pqarrow/arrowutils/arrow.go
snapshot.go
table.go
table_test.go

Use the provided `TotalRecordSize` util from the arrow package to correctly calculate record sizes.

use arrow pkg util for total record size

---

go.mod
query/memory.go
query/physicalplan/physicalplan.go
recovery/recovery.go
table.go

This introduces a new type of `memory.Allocator` that acts as a wrapper around the arrow `GoMemoryAllocator` which will account for the number of bytes allocated but not yet freed and will panic if that limit is exceeded.
In addition it adds a recovery step into the query engine, where if a child go routine panics in the query engine, the engine will capture that panic and return an error instead.

Query limits

---

db_test.go
logictest/logic_test.go
pqarrow/arrowutils/merge.go
pqarrow/arrowutils/nullarray.go
pqarrow/arrowutils/utils.go
query/memory.go
query/physicalplan/aggregate.go
query/physicalplan/distinct.go
query/physicalplan/filter.go
query/physicalplan/project.go

This adds a couple unit tests, but also adds a allocator leak check to the logic tests.
It fixes a lot of the leaks that were uncovered when adding the unit tests.
NOTE: that the check is skipped for the ordered aggregate operator because I was unable to get that one to work.

Fix limit leaks

---

db.go
table.go

This setting would previously only be applied when rotating a table block at write time. However, table blocks are also rotated/persisted on Close. This commit adds a check in Close and on recovery to only persist a table block if manual block rotation is not specified.

*: respect WithManualBlockRotation on Close

---

db_test.go
snapshot.go

We wait above the removed check for the snapshot to be written, so the check is unnecessary.

*: remove eventual check from TestDBRecover

---

db.go
snapshot.go
snapshot_test.go
table.go

Small refactor inject a writer dependency into `snapshotAtATX` which allows for a new function `StoreSnapshot` that can write an external snapshot into the snapshot directory.

Store snapshot

---

pqarrow/builder/optbuilders.go

Turns out I had this locally all the time and never made the PR. 
This is needed for https://github.com/parca-dev/parca/pull/3448.

pqarrow/builder: Add Value to OptInt64Builder

---

compaction_test.go
db.go
db_test.go
dynparquet/example.go
table_test.go

Made clearing the storage a little more natural, and with fewer footguns. Now it uses `db.Close` to perform clear storage, which means that it's no longer valid to use this DB afterwards.
This is preferable to previously with `DropStorage` because the wal isn't meant to be live reloaded and that created a lot of footguns. So instead to acheive the same results one would clear the db storage, and reopen the database again. 
```
db.Close(WithClearStorage())
db = c.DB(....)
```

Cleanup db

---

logictest/testdata/exec/filter/filter

Adds logic tests for the filter fixes in the previous commit `91e1c15`

added DNE filter logictests

---

compaction.go
db.go

Adds a new columnstore option to ensure compaction after recovering databases.

compaction after recover option

---

db.go
granule.go

There are cases where the context gets canceled and granule collection would not react.

*: listen to context cancellation when collecting records

---

granule.go
table.go

This prevents snapshots from racing with dropping a pending block hopefully this addresses #514 
[edit] Updates `PartsForTx` function to not return records that may have been released

Have the `dropPendingBlock` function wait for writes

---

query/logicalplan/builder.go
query/logicalplan/expr.go
query/logicalplan/logicalplan_test.go

Expands the Expr interface to include a Clone() method which returns a copy of the original expression

Expr: Clone

---

binaryscalarexpr.go
binaryscalarexpr_test.go

Previously, if a column chunk had at least one null value, we would automatically further filter it in the execution engine. However, there are cases where we can rely on min/max values as long as they are non-null and the column chunk is not all nulls to filter out column chunks. This greatly reduces load on the execution engine.

*: filter out column chunks with some null values

---

db.go
db_test.go
query/logicalplan/logicalplan.go
query/physicalplan/physicalplan.go
table.go

Adds an option to the query engine to perform queries only against the in memory portion of the db.

Query engine in memory only

---

db_test.go
pqarrow/arrow.go
table.go

Previously we weren't performing physical projections on returned arrow records which caused discrepancy with the data that was returned for a given query whether it was in arrow or parquet format. This fixes that discrepancy by running the physical projections on arrow records to drop columns that are not included in the query.

Fix physical projections

---

pqarrow/builder/optbuilders.go

Adding the SetNull to the baseBuilder makes it available to all other builders too.

Add `SetNull(i int)` to builders

---

db_test.go
query/logicalplan/expr.go
query/physicalplan/physicalplan.go
query/physicalplan/project.go

Since fixing the projection pushdowns to also apply to in-memory arrow records we no longer have a way to wildcard select all columns.
This adds a new logicalplan Expr that allows projection of all columns.

Project all

---

compaction.go
db.go

Previously, the compactor pool was not running during WAL replay. This could cause memory blow-ups on the first compactions after a WAL replay since there would be a lot of l0 parts processed at the same time.
Starting the compactor pool before WAL replay causes WAL replay to slow down a bit but with the good property that data is compacted during WAL replay and memory spikes are avoided. Also, recovery code already expected the compactor pool to be started.
This commit also removes the CompactAfterRecovery option given it is not needed any more.

db: start compactor pool before replaying WAL

---

db.go
db_test.go
snapshot.go

Since we added snapshots on close, it is possible that a large enough block size causes every close to produce a large invalid snapshot. This can cause an instance to run out of disk space quickly if not handled.
This commit simply removes all snapshots greater than the loaded snapshot since they are invalid by definition.

db: clean up snapshots greater than valid snapshot

---

compaction.go
dynparquet/schema.go
parts/part.go
parts/part_test.go
table.go

This reduces the number of open cursors during compaction and reduces memory usage. On a production WAL (Polar Signals project), the maximum memory usage went from 27GB to 8.5GB (70% reduction). Replay time has also been slightly improved:
```
goos: darwin
goarch: arm64
│ benchmain  │           benchpspart            │
│   sec/op   │   sec/op    vs base              │
Replay-12   67.26 ± 3%   63.82 ± 1%  -5.12% (p=0.002 n=6)
│  benchmain   │            benchpspart             │
│     B/op     │     B/op      vs base              │
Replay-12   243.6Gi ± 2%   235.2Gi ± 2%  -3.42% (p=0.004 n=6)
│  benchmain  │         benchpspart          │
│  allocs/op  │  allocs/op   vs base         │
Replay-12   2.492G ± 2%   2.500G ± 2%  ~ (p=0.589 n=6)
```

compaction: treat non-overlapping l0 parts as a single row group

---

query/logicalplan/expr.go
query/logicalplan/optimize.go
query/logicalplan/optimize_test.go

Saves cpu and memory to compile the optimization once

remove hashed optimization regexp compile step

---

compaction.go
db.go

Since we recently changed replay to not start compactions, add this option back in so that callers can ensure data is compacted after replay.

db: add CompactAfterRecovery option back in

---

compaction.go
db.go

This allows skipping the compaction of unimportant tables.

db: allow specifying a subset of tables to compact after recovery

---

index/lsm.go
index/lsm_test.go
parts/part.go
snapshot.go
table.go

This is useful when replaying a snapshot to replay the part into the correct level of the lsm

lsm: store the part compaction level

---

index/lsm.go
store.go

Otherwise, compaction races with snapshots.

lsm: hold read lock on iterate

---

pqarrow/arrow.go
query/logicalplan/expr.go
query/logicalplan/optimize.go
query/logicalplan/optimize_test.go

If the projection matches the entire arrow records simply return the whole record

optimize arrow project

---

db.go
index/lsm.go
index/lsm_test.go
parts/part.go
table.go

This reduces l0 compaction memory usage by half. Also, no-op compactions are avoided (i.e. single l1 parts that are too big).

index: don't sort merge non-overlapping l0 parts

---

dynparquet/schema.go
table.go

This commit removes SortingWriter for compaction, given it increases our memory usage. Since we now rely on l0 parts being sorted, we can use a more efficient non-sorting writer for compaction.
On a prod wal replay:
```
benchstat benchmain_mem benchnew_mem
goos: darwin
goarch: arm64
│ benchmain_mem │           benchnew_mem            │
│    sec/op     │   sec/op    vs base               │
Replay-12      34.99 ± 0%   23.21 ± 1%  -33.66% (p=0.002 n=6)
│ benchmain_mem │            benchnew_mem             │
│     B/op      │     B/op      vs base               │
Replay-12    50.54Gi ± 2%   42.07Gi ± 4%  -16.77% (p=0.002 n=6)
│ benchmain_mem │           benchnew_mem            │
│   allocs/op   │  allocs/op   vs base              │
Replay-12     131.9M ± …
```

*: do not use SortingWriter for compaction

---

db.go

This log message would have saved us a lot of time during a recent incident.

db: log error on setup

---

db.go
db_test.go
store.go
table_test.go

Add constant value to make the code more readable. I believe it should be more elegant. 
Could you help review it when you have time? Thanks!

Add constant value to make the code more readable

---

dynparquet/row.go
dynparquet/schema.go
pqarrow/parquet.go
table.go

Previously, non-overlapping arrow records (L0 parts) were each converted to a parquet file and then merged. This commit shortcuts this process by directly converting all L0 arrow records into a parquet part.
This reduces L0 compaction memory usage substantially.
```
│ benchmain_alltables │     benchl0direct_sameschema      │
│       sec/op        │   sec/op    vs base               │
Replay//stacktraces/0-12               27.68 ± 3%   24.88 ± 1%  -10.12% (p=0.002 n=6)
Replay//stacktraces/1-12               11.47 ± 1%   11.53 ± 1%        ~ (p=0.589 n=6)
Replay//aggregate_view/0-12           14.110 ± 3%   7.955 ± 2%  -43.62% (p=0.002 n=6)
Replay//aggregate_view/1-12            9.559 ± 2%   9.677 ± 2%        ~ (p=0.132 n=6)
Replay//labels_view/0-12               9.866 ± 2%   6.836 ± 4% …
```

table: write arrow records directly to parquet file during compaction

---

cmd/parquet-reencode/main.go
dynparquet/reader_test.go
dynparquet/schema.go
index/lsm_test.go
parts/part.go
table.go

This applies specifically to tables with a unique primary index. This reduces
the amount of data that is converted to parquet and also avoids a merge step
for L0 compactions.
```
│ benchmain_labels │         bench_distinct_sw          │
│      sec/op      │   sec/op     vs base               │
Replay//labels_view/0-12         7.104 ± 2%   2.793 ± 15%  -60.68% (p=0.002 n=6)
│ benchmain_labels │          bench_distinct_sw          │
│       B/op       │     B/op      vs base               │
Replay//labels_view/0-12      10.180Gi ± 2%   5.513Gi ± 3%  -45.84% (p=0.002 n=6)
│ benchmain_labels │         bench_distinct_sw          │
│    allocs/op     │  allocs/op   vs base               │
Replay//labels_view/0-12        52.25M ± 2%   20.84M ± 0%  -60.11% …
```

table: run distinct on arrow records during compaction

---

table.go

Hedge against a scenario where the new active block and the preivously uploaded block have the same timestamp in their ulid. This caused queries to discard the uploaded block erroniously.

Fix: Data not found on rotate

---

aggregate_test.go
query/physicalplan/aggregate.go

The previous version of the code was not working with records where dynamic columns might appear/disappear on each callback call.

physicalplan: fix aggregation on dyn cols where not all cols are in record

---

db.go
db_test.go

This allows checking whether a DB exists, and dropping a DB.

db: add GetDB and DropDB

---

db.go

The contents were removed, but not the dir itself.

db: remove database dir on DropDB

---

dynparquet/hashed.go
dynparquet/schema.go
dynparquet/schema_test.go
pqarrow/arrowutils/arrow.go
pqarrow/parquet.go

These two commits reduce some of the biggest offenders in terms of the number of allocated objects (50% of a production profile), which greatly affects GC. The improvements on a replay of a production WAL are already noticeable but I think this change should shine in steady-state memory usage:
```
│ benchmain  │             benchnew              │
│   sec/op   │   sec/op    vs base               │
Replay-12   8.747 ± 2%   6.359 ± 4%  -27.30% (p=0.002 n=6)
│  benchmain   │              benchnew               │
│     B/op     │     B/op      vs base               │
Replay-12   22.85Gi ± 1%   20.21Gi ± 0%  -11.57% (p=0.002 n=6)
│  benchmain  │              benchnew              │
│  allocs/op  │  allocs/op   vs base               │
Replay-12   146.8M ± 2% …
```

*: remove unnecessary allocations

---

pqarrow/parquet.go

This should reduce allocations from any to []byte

use parquet.ByteArrayValue instead of ValueOf

---

dynparquet/schema.go

This allows returning pooled parquet value buffers back to the sync.Pool managed by parquet during compaction. It should slightly reduce our memory usage. Memory usage should be further reduced once dictionary page pooling is implemented in parquet (WIP).

dynparquet: make remappedPages releasable

---

pqarrow/parquet.go
pqarrow/parquet_test.go

Previously, we were building a scratchRows buffer column by column before writing to a writer. Profiles show that this buffer is not very efficiently reused, most likely since its scope is limited to a single compaction. These allocations end up being 7% of allocations on prod. This commit changes the arrow->parquet conversion back to row-by-row but avoids allocations. Benchmarks show that the runtime is not affected that much:
```
goos: darwin
goarch: arm64
pkg: github.com/polarsignals/frostdb/pqarrow
│ benchmainnoscratch │           benchnew           │
│       sec/op       │   sec/op     vs base         │
RecordsToFile-12          278.9µ ± 3%   278.5µ ± 1%  ~ (p=0.818 n=6)
│ benchmainnoscratch │              benchnew               │
│        B/op        │     B/op      vs base …
```

pqarrow: change back to row-by-row conversion but write directly

---

go.mod
go.sum

Some weird behavior started happening likely to dictionary page pooling.

deps: point parquet-go back to main

---

cmd/parquet-tool/cmd/dump.go
cmd/parquet-tool/cmd/find.go
cmd/parquet-tool/cmd/root.go
cmd/parquet-tool/cmd/rowgroup.go
cmd/parquet-tool/cmd/util.go

Adds
- rowgroup command to dump the index for an individual row group
- column command to dump the data in a column in a row group
- find: Support matching a rowgroup against multiple column matchers at once

Parquet tool

---

index/lsm.go
index/lsm_test.go
parts/arrow.go
parts/parquet.go
parts/part.go
parts/part_test.go
snapshot.go
table.go

Now that Part is an interface we can split the Parquet buffer and Arrow record implementations into two distinct implementations

Split arrow part and parquet part

---

pqarrow/builder/optbuilders.go

Since reflect.SliceHeader is deprecated we switched to using unsafe.Slice. However we used data[0] as the pointer to the data of the slice. Which worked until the data array was nil.
This changes that to use unsafe.SliceData instead which hedges against an empty slice
Fixes #614

Fix use of unsafe.Slice: Use unsafe.SliceData

---

Makefile
dynparquet/example.go
examples/aggregations/aggregations.go
logictest/logic_test.go
logictest/runner.go
logictest/testdata/exec/aggregate/aggregate
pqarrow/builder/utils.go
query/logicalplan/validate.go
query/physicalplan/aggregate.go
query/physicalplan/physicalplan.go
query/physicalplan/project.go

This is very much a work in progress and could also be all wrong. 
This is an attempt at adding support for float64 aggregations. At this point, the aggregation works but the values are all wrong. Somehow the conversion of the value to float is wrong and I can't quite see why that is. I've been using the `examples/aggregation.go` to test it and it gives results of `[1.5e-322 1.5e-322 2e-322]` so I've got something wrong. 
If you could point me in the correct direction I could make the changes, or if I'm completely wrong let me know a better way. 
Fixes https://github.com/polarsignals/frostdb/issues/587

feat: initial work for aggregations with float64

---

dynparquet/record_builder.go
dynparquet/record_builder_test.go

Support repeated columns for all base types `[]int64` `[]float64`  `[]bool` `[]string`.   Use all supported tags on this column like other base columns( set encoding ,compression etc)
Since we deal with slices I took the liberty to make repeated fields nullable by default. 
Example
```go
type Example struct {
StringDict []string `frostdb:",rle_dict"`
}
```

Support repeated columns for Generic Record Builder

---

go.mod
go.sum
pqarrow/arrowutils/sort.go
pqarrow/arrowutils/sort_test.go

This is extract from a previous PR #461.

pqarrow/arrowutils: Add SortRecord and ReorderRecord

---

dynparquet/record_builder.go
dynparquet/record_builder_test.go

Before, we had `null` tag that set schema column to nullable. However the base types allowed were `int64|float64|bool|string`.
This begged the question, what is `null`? for a `nullable` field of type `int64` do we interpret `0` as `null`?, probably not. We were offering option for something that was impossible to represent.
Fortunately, we can safely represent null values with out type system. For
base types   `*int64|*float64|*bool|*string` defines nullable base types.
This commit add support for both `int64|float64|bool|string` and `*int64|*float64|*bool|*string` for base types . This works with dynamic columns too.
With this change `null` tag is redundant so It was removed. Fields of type `*int64|*float64|*bool|*string` will automatically generate nullable schema
column.
NOTE: I also …

Support nullable base types for (*Build[T])

---

pqarrow/arrow.go
pqarrow/builder/recordbuilder.go
table.go

This frees the dictionaries between record creations so that stale dictionary values aren't being held.
We were seeing huge storage spikes resulting from this dictionary bloat.

parquet/converter: New Record call ResetFull on dictionary builders

---

pqarrow/parquet.go
pqarrow/parquet_test.go

This function is called on a hot path. I couldn't resist the temptation to squeeze some performance gains from it.
Benchmark results:
```
goos: darwin
goarch: amd64
pkg: github.com/polarsignals/frostdb/pqarrow
│    old.txt    │             new.txt             │
│    sec/op     │    sec/op     vs base           │
RecordDynamicCols-8   1470.0n ± ∞ ¹   792.6n ± ∞ ¹  ~ (p=1.000 n=1) ²
¹ need >= 6 samples for confidence interval at level 0.95
² need >= 4 samples to detect a difference at alpha level 0.05
│   old.txt   │            new.txt             │
│    B/op     │    B/op      vs base           │
RecordDynamicCols-8   936.0 ± ∞ ¹   536.0 ± ∞ ¹  ~ (p=1.000 n=1) ²
¹ need >= 6 samples for confidence interval at level 0.95
² need >= 4 samples to …
```

Performance improvement on pqarrow.RecordDynamicCols

---

dynparquet/dynamiccolumns.go
dynparquet/dynamiccolumns_test.go

Benchmark result:
```
goos: darwin
goarch: amd64
pkg: github.com/polarsignals/frostdb/dynparquet
│   old.txt    │             new.txt             │
│    sec/op    │    sec/op     vs base           │
Deserialization-8   715.9n ± ∞ ¹   443.1n ± ∞ ¹  ~ (p=1.000 n=1) ²
¹ need >= 6 samples for confidence interval at level 0.95
² need >= 4 samples to detect a difference at alpha level 0.05
│   old.txt   │            new.txt             │
│    B/op     │    B/op      vs base           │
Deserialization-8   592.0 ± ∞ ¹   432.0 ± ∞ ¹  ~ (p=1.000 n=1) ²
¹ need >= 6 samples for confidence interval at level 0.95
² need >= 4 samples to detect a difference at alpha level 0.05
│   old.txt   │            new.txt             │
│  allocs/op  │  allocs/op   vs …
```

Optimize dynparquet..deserializeDynamicColumns

---

dynparquet/dynamiccolumns.go
dynparquet/dynamiccolumns_test.go

This function is used in a hot path.
Benchmark results
```
goos: darwin
goarch: amd64
pkg: github.com/polarsignals/frostdb/dynparquet
│   old.txt    │             new.txt             │
│    sec/op    │    sec/op     vs base           │
Serialize-8   480.5n ± ∞ ¹   314.6n ± ∞ ¹  ~ (p=1.000 n=1) ²
¹ need >= 6 samples for confidence interval at level 0.95
² need >= 4 samples to detect a difference at alpha level 0.05
│   old.txt   │            new.txt             │
│    B/op     │    B/op      vs base           │
Serialize-8   248.0 ± ∞ ¹   120.0 ± ∞ ¹  ~ (p=1.000 n=1) ²
¹ need >= 6 samples for confidence interval at level 0.95
² need >= 4 samples to detect a difference at alpha level 0.05
│   old.txt   │            new.txt             │
│ …
```

Optimize dynparquet.serializeDynamicColumns

---

query/expr/filter.go

`(true && boolean) == boolean` no need for extra work. I also removed a comment that might be out of place, `right` is on the stack, there is no heap allocation.

Simplify (*AndExpr).Eval

---

pqarrow/parquet.go
pqarrow/parquet_test.go

From #599 It indicated to me any gains here will be good for `parca`. This is my first pass on it, there are still many opportunities to squeeze more performance from it.
Benchmark results
```
goos: darwin
goarch: amd64
pkg: github.com/polarsignals/frostdb/pqarrow
│   old.txt    │             new.txt             │
│    sec/op    │    sec/op     vs base           │
RecordsToFile-8   497.1µ ± ∞ ¹   364.1µ ± ∞ ¹  ~ (p=1.000 n=1) ²
¹ need >= 6 samples for confidence interval at level 0.95
² need >= 4 samples to detect a difference at alpha level 0.05
│    old.txt    │             new.txt              │
│     B/op      │     B/op       vs base           │
RecordsToFile-8   56.57Ki ± ∞ ¹   32.84Ki ± ∞ ¹  ~ (p=1.000 n=1) ²
¹ need >= 6 samples for …
```

Optimize pqarrow.recordToRows

---

pqarrow/parquet.go
pqarrow/parquet_test.go

Previously we were operating under assumptions that repeated fields were dictionary of `*array.Binary`.
This commit implements conversion on all arrow arrays of repeated base types `int64|float64|bool|string`
I have also added `*array.Binary` in the mix although it is not categorized as base type (Based on the use, It will make sense to introduce binary type in our schema proto)

Support repeated fields of all base types on recordToRows

---

pqarrow/arrowutils/groupranges.go

Add *array.String dictionary handling in arrowutils.GetGroupsAndOrderedSetRanges

---

dynparquet/schema.go
dynparquet/schema_test.go

This commit
- Adds test (There were no test covering this function)
- Introduce a new implementation for merging column sets that can be reused.
- Use `*sync.Pool` to reuse the new dynamic column set merger
Benchmark result
```
goos: darwin
goarch: amd64
pkg: github.com/polarsignals/frostdb/dynparquet
│   old.txt   │               new.txt               │
│   sec/op    │   sec/op     vs base                │
MergeDynamicColumnSets-8   2.220µ ± 1%   1.330µ ± 1%  -40.09% (p=0.000 n=10)
│   old.txt   │              new.txt               │
│    B/op     │    B/op     vs base                │
MergeDynamicColumnSets-8   1104.0 ± 0%   544.0 ± 0%  -50.72% (p=0.000 n=10)
│   old.txt   │              new.txt               │
│  allocs/op  │ allocs/op …
```

Optimize dynparquet.MergeDynamicColumnSets

---

logictest/testdata/exec/projection/math_projection
query/logicalplan/expr.go
query/physicalplan/project.go
sqlparse/visitor.go

After this, we can remove the average aggregation and instead have a logical optimizer that replaces an average expression with `sum(col) / count(col) as avg(col)`.
This is also some groundwork, so we can perform `count * period` calculations in Parca, which is required so we can compare profiling data with different periods.
@thorfour @asubiotto

*: Add mathematical projections

---

internal/records/record_builder.go
internal/records/record_builder_test.go
samples/example.go

This commit uses `internal/records.Build` to build `arrow.Record`  for `Samples`. The plan is
to eventually remove all manual `arrow.Record` generation in tests.
Also, testing package was changed from `records` to `records_test` because we uses Samples to test the builder which causes cyclic dependency. Testing package change is basically a NOOP change(everything stays the same when testing just a different test binary name.)

Remove manual record building for Samples

---

pqarrow/arrowutils/sort_benchmark_test.go
pqarrow/arrowutils/sort_test.go

This was supposed to be part of #635
I will work on benchmarking `ReorderRecord` separately, I am not satisfied with `ReorderRecord` api, will think more about it( we pass `memory.Allocator` together with `context.Context`, we need to only pass `context.Context` like what `compute` apis do).

Add BenchmarkSortRecord

---

pqarrow/arrowutils/sort.go
pqarrow/arrowutils/sort_test.go

We already pass `context.Context` and use `compute`. Anyone who needs a custom Allocator can use `compute.WithAllocator`.

Remove explicit memory.Allocator for arrowutils.ReorderRecord

---

pqarrow/builder/utils.go

I came across this while working on logic tests. `*array.BinaryDictionaryBuilder` column should work for both `string` and `[]byte`.

Fix appending strings to *array.BinaryDictionaryBuilder column

---

aggregate_test.go
db_test.go
examples/aggregations/aggregations.go
examples/simple/simple.go
snapshot_test.go
table.go
table_test.go

We are wrapping `(*Table).InsertRecord` call but were ignoring the transaction . This commit ensures we match `(*Table).InsertRecord`  return signature.
I also added godoc on the method

Return transaction on (*GenericTable[T]).Write

---

compaction.go
db.go
db_test.go
dynparquet/schema.go
index/lsm.go
index/lsm_list.go
index/lsm_test.go
snapshot.go
table.go

Adds support for persistent LSM files.
If storage path is enabled then persistent LSM files are used instead of temporary files. During startup, the database will recover parts from the LSM files and insert them into the index into the corresponding levels. 
If persistent LSM is configured then snapshots will not write those compacted parts into the snapshot file, and will only write the L0 parts.

Persistent lsm

---

logictest/testdata/exec/filter/filter
query/logicalplan/expr.go
query/physicalplan/binaryscalarexpr.go
query/physicalplan/binaryscalarexpr_test.go

Instead of implementing individual functions for each BinaryScalar operation, we'll now use the arrow `compute` package. It already implements most of the heavy lifting for us. 
Once we pass in the array and the scalar, we can convert the data back to a `*array.Boolean`. Walking this array, we construct the bitmap like we did before. 
It cleans up a lot of duplicate code and removes the need to add new functions for new Arrow types. 
Given the quality of live improvement, the performance impact is fine:
```
name                         old time/op    new time/op    delta
BinaryScalarOperation/==-24    3.39ms ± 2%    3.76ms ± 7%  +11.00%  (p=0.008 n=5+5)
BinaryScalarOperation/!=-24    11.2ms ± 3%    11.4ms ± 1%   +1.64%  (p=0.032 n=5+4)
BinaryScalarOperation/<-24     6.00ms ± 6%    6.25ms …
```

query/physicalplan: Use arrow compute package for binary scalar expressions

---

pqarrow/arrowutils/merge.go
pqarrow/arrowutils/merge_test.go
query/physicalplan/ordered_aggregate.go
query/physicalplan/ordered_synchronizer.go

This is helpful for merging multiple sorted records but only keeping the first e.g. 1000 rows.

pqarrow/arrowutils: Add optional limit to MergeRecords

---

pqarrow/arrowutils/sort.go
pqarrow/arrowutils/sort_test.go

The new name reflects what the function does, we are not ordering anything we are just taking specific rows.

Rename ReorderRecord to Take

---

pqarrow/arrowutils/sort.go

The result arrow.Record has the same number of rows as the the input indices array.
This is part of #672

fix number of rows for arrowutils.Take record

---

pqarrow/arrowutils/sort.go

`r` and `indices` are externally managed resources. Owning them increases ref
count ,since we never releases them they will leak when `r` has no dictionary field.
There is no need to own these resources inside `Take`.
This is part of #672

Fix memory leak in arrowutils.Take

---

pqarrow/builder/optbuilders.go

Array bounds check is already handled by Go compiler.

Remove bounds check from Opt  Builders

---

db.go

After reading the `TODO` and inspecting the code. I think it is safe to remove it now. From my understanding the `TODO` reminds us that the record added to `lsm` is not pre hashed and recommends we prehash before writing to wal which we currently do.
cc @asubiotto

Remove TODO since we prehash before wal now

---

design/index_files.md

I was reading the rendered rfc and this table was not visible. I had to switch to RAW to read it.
cc @thorfour

Format markdown table for index_lsm design doc

---

db_test.go
index/lsm.go
snapshot.go
table.go

Snapshot's and Compaction could deadlock. This fixes that.
Compactions wait for the watermark to reach the newest transaction in the L0 level.
Snapshots were creating a write tx, but where then calling index.Snapshot which acquires the index.Compaction lock.
This could result in a deadlock if a write came in that was newer than the snapshot tx and the compaction was waiting for the watermark to get to that, but the snapshot was waiting to commit it's tx waiting for the compaction lock.
Instead of acquiring a write tx we need only to get a read tx so we don't block the watermark. We also do not need to log to the WAL for snapshots because we do nothing with that information on replay.

Fix index deadlocks

---

index/compaction.go
snapshot.go
table.go

Fixes a deadlock that can occur if the reading goroutine exits but strands the collect row groups routine.

Fix deadlock

---

db_test.go
index/compaction.go
table.go

Fixes compaction being able to write files without the `compaction_tx` metadata.
Also no longer treats a missing `compaction_tx` as an error, and simply downgrades the part tx.

Fix missing compaction tx

---

recovery/recovery.go

Closes #539 adds an optional logger to the `recovery.Do` function to log the stack trace.

recovery: added optional logger

---

table.go

Previously if collectRowGroups returned with an error (e.g. context cancellation), the rowGroups channel would not be closed. This commit closes the channel in a defer so that the cleanup code correctly exits the `for rowGroups` release logic.

table: avoid deadlock when releasing parts

---

db.go
db_test.go
tx_list.go

Before a recent fix, we would rely on txn IDs to always be inserted into the TxPool to bubble up the watermark correctly. This commit adds a mechanism to notify the TxPool that the watermark has been changed, which is required in order to bubble up the watermark correctly.

db: notify txpool of watermark changes

---

db_test.go
index/compaction.go
snapshot.go

Adds a unit test that artificially causes a race between snapshots and compactions to cause newer data than the snapshot tx to end up in the snapshot. 
However due to index insert writes rejecting inserts with a tx less than what's already been inserted it ensures that we don't end up with duplicate data. 
There was a bug with the in-memory LSM that this test found and was fixed. It wasn't correctly setting the compaction tx.

Test snapshot isolation

---

index/levels.go
index/lsm.go
parts/arrow.go
parts/parquet.go
parts/part.go
snapshot.go

Part one of #722 
This moves more of the snapshot logic into the index itself instead of in the snapshot layer. 
Previously the snapshot would know to walk `L0` parts and write them to the file, and then depending on how the index was configured it would either write the `L1+` parts to the file or it would skip them and call `index.Snapshot` at the end.
This moves the handling of levels all into the index where it belongs. Now Snapshot provides a writer function for parts, and a directory for the snapshot and just calls `index.Snapshot` for each table. 
Next part will be to move the snapshot into it's own package.

snapshot: refactor to simplify

---

pqarrow/arrowutils/sort.go

I've added int16 and int32 along the way.
FrostDB doesn't use them for now but it doesn't hurt here and probably gets rid of a panic once we do.

pqarrow/arrowutils: Support sorting for uints

---

logictest/testdata/exec/filter/filter
logictest/testdata/exec/filter/filter_contains
logictest/testdata/plan/filter/filter
query/logicalplan/expr.go
query/physicalplan/binaryscalarexpr.go
query/physicalplan/filter.go
sqlparse/visitor.go

Similar to `OpContains`, adding `OpNotContains` now. 
It reuses the same `BinaryScalarOperation` but sets a `not` flag to negate all results. 
@brancz, you were right about using `contains` over `|=`. This is because it is obvious that adding `not contains` now and the `!=` would have conflicted. I decided to call it `contains` and not `like` because like has some additional properties that this operator doesn't fulfill.

Add `OpNotContains` filter

---

table.go
table_test.go

There was a potential deadlock when a query was canceled during scan. It could cause the part to not be placed into the channel (which are all released) but wouldn't decrement the reference count. This has it decrement the reference count if the context is canceled.
This closes #741

741 deadlock

---

snapshot.go

This got missed when moving to top-level snapshot directories. We need to be cleaning up the whole snapshot directory not just the snapshot file.

snapshot: On snapshot failure cleanup correctly

---

bench_test.go
db.go
snapshot.go

When we were closing the database we may take a snapshot on close. If we do, that snapshot was taking on "offline" snapshot which doesn't acquire the active writeblock.
Because it doesn't acquire an active write block it menat it could race with an active block rotation, which could close the index before the snapshot occurs resulting in a bad snapshot.
This changes the snapshot behavior to always be "online" and acquire the active write block.

Snapshot: Always acquire an ActiveWriteBlock

---

bench_test.go
pqarrow/arrowutils/sort_test.go
pqarrow/builder/optbuilders.go

The reason we want to do this is so that when pooling the builder as part of the `MultiColSorter` we don't reuse the builder's data for a concurrent existing array.

Set OptInt32Builder data to nil

---

internal/records/record_builder.go
internal/records/record_builder_test.go

Hi, long time no see. Wish you all the best. 
Recently I learned the base knowledge of Apache Arrow and read the code for creating Arrow Builder in your project. I noticed that you are only supporting some primitive types in Go, and these types are int64, float64, string, and bool. 
So I would like to help implement builders for other primitive types in Go, such as uint64, uint8, etc.
I also noticed that we should define the values of enums in protobuf, and the type uint64 has already been defined there. So this PR is just a case for what I want to do, and it implements the arrow builder for the type uint64. 
Would like to wait for your opinions or concerns, thanks!

help add the logic of creating arrow builder for the type uint64 in Go

---

query/expr/filter.go
query/expr/filter_test.go
query/logicalplan/optimize.go
query/logicalplan/optimize_test.go

When reading Particulates from blocks (either in-memory or object storage), we can drastically reduce the runtime of global aggregations with no filters. This commit implements the optimization pushdown as a filter.
In case of Max (implemented in this commit) for example, the TrueNegativeFilter memoizes the maximum value seen and filters out any Particulates that will definitely not contribute to the aggregation function (i.e. whose max value is less than the max value seen so far). This drastically reduces global Max queries. For example, on 1.5GB of data, a global Max on an unsorted int64 column went from 900ms to 50ms.

query: add global aggregation function pushdown optimization for Max

---

query/physicalplan/filter.go
query/physicalplan/filter_test.go

Previously, filters run on records would run both the left and right expression on records. However, it is possible to short circuit the evaluation if the left expression evaluates to false on all rows in a record.

physicalplan: short-circuit AndExpr if left side evaluates to false

---

db_test.go
snapshot.go

Previously if we took a snapshot, stopped writing and shutdown the database we would take another snapshot. This snapshot would fail which would cause it to remove the valid snapshot directory.
This changes the behavior of snapshots to first check if a snapshot already exists. If it does validate it and if the snapshot is valid abort taking a new one. If the snapshot is invalid then remove it and perform the snapshot.
Closes #753

Fix: double snapshot data loss

---

parts/arrow.go
pqarrow/parquet.go
pqarrow/parquet_test.go
table_test.go

We preiviously were not detecting uint64 arrow arrays and weren't casting them correctly to an int64 array for Parquet. This adds the switch statement to correctly perform this conversion.
We were also assuming that ONLY dynamic columns needed to have a definition level of 1, but we have other columns that also support nullable values. This removes the dynamic column check and correctly checks the parquet optionality instead.

fix: uint64 persistence

---

query/physicalplan/physicalplan.go

For some reason, this was missing.
It's mostly a copy of the TableScan's Draw method

query/physicalplan: Draw SchemaScan for explain

---

pqarrow/arrow.go
query/physicalplan/binaryscalarexpr.go
query/physicalplan/filter.go
query/physicalplan/filter_test.go
query/physicalplan/regexpfilter.go
table.go

Push the query filter down to the Parquet row group conversion layer. This saves on CPU time when building Arrow records since our row group usage tends to be sparse.
```
name               old time/op    new time/op    delta
Query/MergeAll-10     1.34s ± 1%     0.96s ± 1%  -28.18%  (p=0.000 n=10+10)
Query/Merge-10        1.33s ± 2%     0.96s ± 1%  -28.27%  (p=0.000 n=10+9)
name               old alloc/op   new alloc/op   delta
Query/MergeAll-10    5.51GB ± 0%    5.64GB ± 1%   +2.33%  (p=0.000 n=10+9)
Query/Merge-10       5.52GB ± 1%    5.65GB ± 1%   +2.35%  (p=0.000 n=10+10)
name               old allocs/op  new allocs/op  delta
Query/MergeAll-10     34.1M ± 0%     50.6M ± 0%  +48.35%  (p=0.000 n=10+10)
Query/Merge-10        34.1M ± 0%     50.6M ± 0%  +48.34%  (p=0.000 n=10+9)
```

Push down query filter to Parquet conversion.

---

pqarrow/arrow.go

```bash
name               old time/op    new time/op    delta
Query/MergeAll-10     850ms ± 1%     867ms ± 1%  +2.04%  (p=0.000 n=8+10)
Query/Merge-10        854ms ± 2%     861ms ± 1%    ~     (p=0.075 n=10+10)
name               old alloc/op   new alloc/op   delta
Query/MergeAll-10    4.55GB ± 1%    4.25GB ± 1%  -6.47%  (p=0.000 n=10+10)
Query/Merge-10       4.55GB ± 1%    4.27GB ± 1%  -6.10%  (p=0.000 n=10+10)
name               old allocs/op  new allocs/op  delta
Query/MergeAll-10     47.6M ± 0%     47.6M ± 0%  +0.01%  (p=0.000 n=10+10)
Query/Merge-10        47.6M ± 0%     47.6M ± 0%  +0.01%  (p=0.000 n=10+10)
```

optimize: skip reading whole column if it's been preread

---

pqarrow/arrow.go
query/physicalplan/binaryscalarexpr.go
query/physicalplan/binaryscalarexpr_test.go
query/physicalplan/filter.go
query/physicalplan/filter_test.go
query/physicalplan/regexpfilter.go
table.go

The parquet filter pushdown was a good idea, but the implementation ran into a problem with filtering repeated values. We cannot rely on the row index to filter a slice of parquet values for a repeated field. 
At present I don't have a non O(N) way of filtering a repeated list, so I need to revert these changes for now.

Revert parquet filtering

---

internal/records/record_reader.go

Similar to the generic builder I've added a reader.
It can read multiple records and returns the passed struct when calling Value(i).
This makes it super easy to read the records back to structs and compare against some expected values.
```go
type struct3 struct {
Field1 int64 `frostdb:",asc(0)"`
Field2 int64 `frostdb:",asc(1)"`
Field3 int64 `frostdb:",asc(1)"`
}
expected := []struct3{
// record1
{Field1: 1, Field2: 2, Field3: 0},
{Field1: 1, Field2: 3, Field3: 0},
// record2
{Field1: 1, Field2: 0, Field3: 2},
{Field1: 1, Field2: 0, Field3: 3},
// record3
{Field1: 1, Field2: 1, Field3: 1},
{Field1: 2, Field2: 2, Field3: 2},
}
reader := records.NewReader[struct3](recs...)
rows := reader.NumRows()
require.Equal(t, int64(len(expected)), rows)
actual := make([]struct3, rows)
for i := 0; i < …
```

internal/records: Create generic reader

---

pqarrow/builder/optbuilders.go
pqarrow/builder/optbuilders_test.go
pqarrow/builder/utils.go

We mostly need this because it supports the Set and Add methods compared to the upstream Float64Builder.

pqarrow/builder: Add OptFloat64Builder

---

pqarrow/arrowutils/schema.go
pqarrow/arrowutils/schema_test.go

Sometimes, before using MergeRecords, we want to make sure that all records have the same schema. If they don't we need to add NullArrays for fields that don't exist. 
This is a modified version of what the OrderedSynchronizer already has.

pqarrow/arrowutils: Add EnsureSameSchema for records

---

go.mod
go.sum
storage/iceberg.go
storage/iceberg_test.go

This addresses a feature request from #838 to be able to have the storage engine expire data files that exceed a certain age.
It does this in two parts; one it will delete the data files from the table by performing a normal table writer where it simply removes the entries from the manifests and then commits the change.
Then once those data files are stranded (i.e no snapshot references them anymore) the maintenance code will deem them to be orphaned files and delete them from the bucket.

Iceberg maintenance

---

query/engine_test.go
query/physicalplan/physicalplan.go

The aggregators exepct to have a final aggregation.
In the concurrency = 1 case we weren't correctly aggregating
because no final aggregation was created.
This removes the requirement for concurrency to be > 1 for a syncronizer
and final aggregation to be created.
Ideally in the future we would just schedule a single aggregation that
handles both being a normal and final aggregation but this is a simple
fix for an edge case that isn't important at this point.
Fixes #769

Fix query concurrency

---

db_test.go
table.go

Check to make sure there is data in the block before calling Persist
Fixes #860

Don't upload a block if it is empty

---

wal/wal.go
wal/wal_test.go

On Truncate(k), if k was logged to the WAL the behavior is unchanged. However, if k had not yet been logged to the WAL, the WAL performed a full reset of the WAL and set the next expected txn to k+1. This is incorrect, since the semantics of truncate are that k becomes the first entry in the WAL after truncation.

wal: correctly set nextTx on Truncate

---

db.go
db_test.go
index/lsm.go
index/lsm_test.go
snapshot.go
table.go

Reopening this tx PR.
Snapshots now grab a write tx. This prevents from other writes coming in and getting compacted into L1+ before the snapshot completes thus allowing tx > snapshot_tx from making it into the snapshot.
Snapshots now also filter out any writes in L0 that are > snapshot_tx from the snapshot write.

722 snapshot tx changes

---

db.go
dst/dst_test.go
index/lsm.go
table.go
wal/wal.go

This PR contains miscellaneous test and bug fixes. See commits for details. This should fix all DST failures so far (run under stress for 100 iterations).

dst: bug and test fixes

---

table.go

This will allow the recovery handler to log stacktraces during panics

table iterator: Pass in the logger to recovery

---

db.go
db_test.go
go.mod
go.sum
index/lsm.go
metrics.go
snapshot.go
table.go
testing_opts.go
wal/wal.go
wal/wal_test.go

At component instantiation time (e.g. db, wal, table), existing metrics are
provided to the components with the correct variable label set. This moves the
metric registration lifecycle to the store level and avoids duplicate
registration panics when e.g. reopening a closed db.

*: move all metrics registration to the store level

---

dst/dst_test.go
table.go
wal/wal.go

This commit updates the verification logic to expect all successfully written
timestamps except when there was an error writing a value to the WAL.
Previously, the fake log store was accumulating correctly written values but
this wasn't much use so it has been changed to accumulate values that could not
be written to the WAL and removing those from the expected values.
These commits are cherry-picked from #895 in preparation of closing that PR and proposing a new method.

dst: fix data verification logic

---

dst/dst_test.go
dst/runtime/run.go
dst/vfs/file.go
dst/vfs/fs.go
dst/vfs/wasm.go
dst/vfs_hooks_nowasm.go
dst/vfs_hooks_wasm.go

This currently exposes the capability to simulate a hard shutdown. Given that this currently causes test failures, it is unused in this PR. A follow up PR will be created to use these hooks and fix the fallout.

vfs: add a VFS wrapper used in deterministic simulation tests

---

db.go

This would otherwise leak goroutines if an error was encountered closing the WAL.
Bug found with DST.

*: clean up txPool even on error

---

dynparquet/reader.go
pqarrow/parquet.go
storage/iceberg.go
store.go

This adds some more context to what exactly is failing to open. Especially helpful for knowing which blocks my be broken.

Add file path to reading error

---

cmd/parquet-tool/cmd/dump.go

The total byte size recorded in the row group represents the uncompressed size, so to calculate the percentage correctly we also need to use the uncompressed pages of the column.

cmd/parquet-tool: Fix percentage calculation

---

cmd/parquet-tool/cmd/root.go
cmd/parquet-tool/cmd/stats.go

While `dump` prints stats per row group, this prints stats for the entire parquet file.

Add stats tool for total file stats

---

pqarrow/arrowutils/sort.go
pqarrow/arrowutils/sort_test.go
query/physicalplan/limit.go
query/physicalplan/sampler.go
query/physicalplan/sampler_test.go

The RunEndEncoded part made my brain melt a couple of times. The Struct part is weird cause it _always_ assumes the fields of a struct a multiple when creating the new struct array with `array.NewStructArray(cols, names)`, so I had to figure that out and adjust the schema. FixedSizeBinary is simple compared to the other two.

pqarrow/arrowutils: Add sorting support for Struct, RunEndEncoded, FixedSizeBinary

---

pqarrow/builder/utils.go

I'm having a hard time reproducing this panic. The if statement is exactly copied from the underlying code, but we are able to give more context here.

pqarrow/builder: Return error with more context instead of panicking
